/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.Gym360.view.employee;

import java.awt.Toolkit;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import main.java.com.Gym360.model.classes.Cliente;
import main.java.com.Gym360.model.dao.ClienteDAO;
import main.java.com.Gym360.util.dates.Dates;
import main.java.com.Gym360.util.ui.CambiarIU;

/**
 *
 * @author tutaa
 */
public class AttendanceRegisterScreen extends javax.swing.JFrame {
        String idClienteSeleccionado;

        /**
         * Creates new form AttendanceRegisterScreen
         */
        public AttendanceRegisterScreen() {
                initComponents();

                this.setTitle("Registro de Asistencia");
                this.setResizable(false);
                this.setLocationRelativeTo(null);
                this.setIconImage(Toolkit.getDefaultToolkit()
                                .getImage(getClass().getResource("/main/resources/images/logo.png")));
                cargarTablaClientes("");
                ponerFecha();
                CambiarIU.deshabilitarBotones(btnConfirmarAsistencia, btnQuitarAsistencia);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelAsistencia = new javax.swing.JPanel();
                pMenu = new javax.swing.JPanel();
                lbBackButton = new javax.swing.JLabel();
                lbBuscar = new javax.swing.JLabel();
                tfBuscar = new javax.swing.JTextField();
                lbClientesActivos = new javax.swing.JLabel();
                lbFecha = new javax.swing.JLabel();
                spTablaClientesActivos = new javax.swing.JScrollPane();
                tTablaClientesActivos = new javax.swing.JTable();
                imgConfirmarAsistencia = new javax.swing.JLabel();
                btnConfirmarAsistencia = new javax.swing.JButton();
                imgQuitarAsistencia = new javax.swing.JLabel();
                btnQuitarAsistencia = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                panelAsistencia.setBackground(new java.awt.Color(245, 245, 245));
                panelAsistencia.setMaximumSize(new java.awt.Dimension(1467, 800));
                panelAsistencia.setMinimumSize(new java.awt.Dimension(1467, 800));
                panelAsistencia.setPreferredSize(new java.awt.Dimension(1467, 800));
                panelAsistencia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                pMenu.setBackground(new java.awt.Color(93, 0, 0));
                pMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbBackButton.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/back.png"))); // NOI18N
                lbBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbBackButtonMouseClicked(evt);
                        }
                });
                pMenu.add(lbBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

                lbBuscar.setBackground(new java.awt.Color(0, 0, 0));
                lbBuscar.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                lbBuscar.setForeground(new java.awt.Color(245, 245, 245));
                lbBuscar.setText("Buscar:");
                lbBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                pMenu.add(lbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, 30));

                tfBuscar.setBackground(new java.awt.Color(231, 231, 231));
                tfBuscar.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfBuscar.setForeground(new java.awt.Color(20, 20, 20));
                tfBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                tfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfBuscarKeyReleased(evt);
                        }
                });
                pMenu.add(tfBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 330, 30));

                panelAsistencia.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 60));

                lbClientesActivos.setBackground(new java.awt.Color(0, 0, 0));
                lbClientesActivos.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
                lbClientesActivos.setForeground(new java.awt.Color(93, 0, 0));
                lbClientesActivos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbClientesActivos.setText("Clientes");
                lbClientesActivos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                panelAsistencia.add(lbClientesActivos,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1470, 50));

                lbFecha.setBackground(new java.awt.Color(0, 0, 0));
                lbFecha.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
                lbFecha.setForeground(new java.awt.Color(102, 102, 102));
                lbFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbFecha.setText("Fecha: 2025-04-06");
                lbFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                panelAsistencia.add(lbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1470, 50));

                tTablaClientesActivos.setBackground(new java.awt.Color(232, 232, 232));
                tTablaClientesActivos.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tTablaClientesActivos.setForeground(new java.awt.Color(20, 20, 20));
                tTablaClientesActivos.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] { { "Juan Pérez", "juan@email.com", " Administrador", "Activo" },
                                                { "María López ", "maria@email.com", "Empleado", "Inactivo" },
                                                { "Carlos Ruiz", "carlos@email.com", "Cliente", "Activo" },
                                                { null, null, null, null } },
                                new String[] { "Nombre", "Correo", "Rol", "Estado" }));
                tTablaClientesActivos.setShowGrid(false);
                tTablaClientesActivos.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tTablaClientesActivosMouseClicked(evt);
                        }
                });
                spTablaClientesActivos.setViewportView(tTablaClientesActivos);

                panelAsistencia.add(spTablaClientesActivos,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 1050, 480));

                imgConfirmarAsistencia.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/main/resources/images/confirmarAsistencia.png"))); // NOI18N
                panelAsistencia.add(imgConfirmarAsistencia,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 700, -1, 60));

                btnConfirmarAsistencia.setBackground(new java.awt.Color(93, 0, 0));
                btnConfirmarAsistencia.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                btnConfirmarAsistencia.setForeground(new java.awt.Color(200, 200, 200));
                btnConfirmarAsistencia.setText("      Confirmar Asistencia");
                btnConfirmarAsistencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnConfirmarAsistencia.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnConfirmarAsistenciaActionPerformed(evt);
                        }
                });
                panelAsistencia.add(btnConfirmarAsistencia,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 700, 360, 60));

                imgQuitarAsistencia.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/main/resources/images/quitarAsistencia.png"))); // NOI18N
                panelAsistencia.add(imgQuitarAsistencia,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 700, -1, 60));

                btnQuitarAsistencia.setBackground(new java.awt.Color(93, 0, 0));
                btnQuitarAsistencia.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                btnQuitarAsistencia.setForeground(new java.awt.Color(200, 200, 200));
                btnQuitarAsistencia.setText("      Quitar Asistencia");
                btnQuitarAsistencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnQuitarAsistencia.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnQuitarAsistenciaActionPerformed(evt);
                        }
                });
                panelAsistencia.add(btnQuitarAsistencia,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 700, 360, 60));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelAsistencia, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelAsistencia, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void tfBuscarKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tfBuscarKeyReleased
                filtrarTablaClientes();
        }// GEN-LAST:event_tfBuscarKeyReleased

        private void tTablaClientesActivosMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tTablaClientesActivosMouseClicked
                int selectedRow = tTablaClientesActivos.getSelectedRow();

                idClienteSeleccionado = (tTablaClientesActivos.getValueAt(selectedRow, 0).toString());
                if (idClienteSeleccionado != null) {
                        CambiarIU.habilitarBotones(btnConfirmarAsistencia, btnQuitarAsistencia);
                }
        }// GEN-LAST:event_tTablaClientesActivosMouseClicked

        private void btnQuitarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {
                cambiarClienteInactivo();
        }

        private void lbBackButtonMouseClicked(java.awt.event.MouseEvent evt) {
                DashboardEmployeeScreen de = new DashboardEmployeeScreen();
                de.setVisible(true);
                this.setVisible(false);
        }

        private void btnConfirmarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {
                cambiarClienteActivo();
        }

        private void ponerFecha() {
                String fecha = "Fecha: " + Dates.obtenerFechaHoy();
                CambiarIU.ponerTextoEtiqueta(lbFecha, fecha);

        }

        private void filtrarTablaClientes() {
                String filtro = tfBuscar.getText().trim();
                cargarTablaClientes(filtro); // Llamamos al método con el filtro actual
        }

        private void cambiarClienteActivo() {
                try {

                        ClienteDAO clienteDAO = new ClienteDAO();

                        Cliente clienteActivo = clienteDAO.obtenerPorId(idClienteSeleccionado);

                        clienteActivo.setEstado("activo");
                        clienteDAO.actualizar(clienteActivo);

                        JOptionPane.showMessageDialog(this,
                                        String.format("El cliente %s se encuentra activo.",
                                                        clienteActivo.getNombre() + " " + clienteActivo.getApellido()),
                                        "Asistencia exitosa", JOptionPane.INFORMATION_MESSAGE);
                        CambiarIU.deshabilitarBotones(btnConfirmarAsistencia, btnQuitarAsistencia);
                        idClienteSeleccionado = null;
                        cargarTablaClientes("");
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this,
                                        "Ocurrió un error al registrar la Asistencia." + e.toString(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }

        }

        private void cambiarClienteInactivo() {
                try {

                        ClienteDAO clienteDAO = new ClienteDAO();

                        Cliente clienteActivo = clienteDAO.obtenerPorId(idClienteSeleccionado);

                        clienteActivo.setEstado("inactivo");
                        clienteDAO.actualizar(clienteActivo);

                        JOptionPane.showMessageDialog(this, "El cliente %s se encuentra inactivo.",
                                        "Asistencia exitosa", JOptionPane.INFORMATION_MESSAGE);
                        cargarTablaClientes("");
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Ocurrió un error al quitar la Asistencia." + e.toString(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }

        }

        public void cargarTablaClientes(String filtro) {
                ClienteDAO ClienteDAO = new ClienteDAO();
                List<Cliente> clientes;

                if (filtro == null || filtro.trim().isEmpty()) {
                        clientes = ClienteDAO.obtenerTodos();
                } else {
                        clientes = ClienteDAO.obtenerPorIdFiltro(filtro); // Método adaptado al campo "nombre"
                }

                // Columnas basadas en la nueva estructura de la tablaCliente
                String[] columnas = { "ID Cliente", "Nombre", "Teléfono", "Email", "Tipo de Membresía", "Saldo",
                                "Estado" };
                DefaultTableModel model = new DefaultTableModel(columnas, 0);

                for (Cliente emp : clientes) {
                        Object[] fila = { emp.getId(), emp.getNombre() + " " + emp.getApellido(), emp.getTelefono(),
                                        emp.getEmail(), emp.getTipoMembresia(), emp.getSaldo(), emp.getEstado() };
                        model.addRow(fila);
                }

                tTablaClientesActivos.setModel(model); // Asegúrate de que esta tabla esté bien inicializada
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnConfirmarAsistencia;
        private javax.swing.JButton btnQuitarAsistencia;
        private javax.swing.JLabel imgConfirmarAsistencia;
        private javax.swing.JLabel imgQuitarAsistencia;
        private javax.swing.JLabel lbBackButton;
        private javax.swing.JLabel lbBuscar;
        private javax.swing.JLabel lbClientesActivos;
        private javax.swing.JLabel lbFecha;
        private javax.swing.JPanel pMenu;
        private javax.swing.JPanel panelAsistencia;
        private javax.swing.JScrollPane spTablaClientesActivos;
        private javax.swing.JTable tTablaClientesActivos;
        private javax.swing.JTextField tfBuscar;
        // End of variables declaration//GEN-END:variables
}
