/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.Gym360.view.employee;

import main.java.com.Gym360.view.admin.inventory.*;
import main.java.com.Gym360.view.admin.users.*;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.EventQueue;
import java.awt.Toolkit;
import javax.swing.UIManager;

/**
 *
 * @author tutaa
 */
public class CreateClient extends javax.swing.JFrame {

	/**
	 * Creates new form ManageUsersScreen
	 */
	public CreateClient() {
		initComponents();
		this.setTitle("Registrar Cliente");
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/main/resources/images/logo.png")));
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelCrearCliente = new javax.swing.JPanel();
                pMenu = new javax.swing.JPanel();
                lbBackButton = new javax.swing.JLabel();
                lbCrearCompra = new javax.swing.JLabel();
                lbNombre = new javax.swing.JLabel();
                tfNombre = new javax.swing.JTextField();
                lbApellido = new javax.swing.JLabel();
                tfApellido = new javax.swing.JTextField();
                lbTelefono = new javax.swing.JLabel();
                tfTelefono = new javax.swing.JTextField();
                lbEmail = new javax.swing.JLabel();
                tfEmail = new javax.swing.JTextField();
                lbSaldo = new javax.swing.JLabel();
                tfSaldo = new javax.swing.JTextField();
                imgCrearCliente = new javax.swing.JLabel();
                btnCrearCliente = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                panelCrearCliente.setBackground(new java.awt.Color(245, 245, 245));
                panelCrearCliente.setMaximumSize(new java.awt.Dimension(1467, 800));
                panelCrearCliente.setMinimumSize(new java.awt.Dimension(1467, 800));
                panelCrearCliente.setPreferredSize(new java.awt.Dimension(1467, 800));
                panelCrearCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                pMenu.setBackground(new java.awt.Color(93, 0, 0));
                pMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/back.png"))); // NOI18N
                lbBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbBackButtonMouseClicked(evt);
                        }
                });
                pMenu.add(lbBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

                lbCrearCompra.setBackground(new java.awt.Color(0, 0, 0));
                lbCrearCompra.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
                lbCrearCompra.setForeground(new java.awt.Color(245, 245, 245));
                lbCrearCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbCrearCompra.setText("REGISTRAR CLIENTE");
                lbCrearCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                pMenu.add(lbCrearCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

                panelCrearCliente.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

                lbNombre.setBackground(new java.awt.Color(0, 0, 0));
                lbNombre.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbNombre.setForeground(new java.awt.Color(20, 20, 20));
                lbNombre.setText("Nombre:");
                panelCrearCliente.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 40));

                tfNombre.setBackground(new java.awt.Color(231, 231, 231));
                tfNombre.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfNombre.setForeground(new java.awt.Color(20, 20, 20));
                tfNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                panelCrearCliente.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 280, 40));

                lbApellido.setBackground(new java.awt.Color(0, 0, 0));
                lbApellido.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbApellido.setForeground(new java.awt.Color(20, 20, 20));
                lbApellido.setText("Apellido:");
                panelCrearCliente.add(lbApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 40));

                tfApellido.setBackground(new java.awt.Color(231, 231, 231));
                tfApellido.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfApellido.setForeground(new java.awt.Color(20, 20, 20));
                tfApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                panelCrearCliente.add(tfApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 280, 40));

                lbTelefono.setBackground(new java.awt.Color(0, 0, 0));
                lbTelefono.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbTelefono.setForeground(new java.awt.Color(20, 20, 20));
                lbTelefono.setText("Telefono:");
                panelCrearCliente.add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 40));

                tfTelefono.setBackground(new java.awt.Color(231, 231, 231));
                tfTelefono.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfTelefono.setForeground(new java.awt.Color(20, 20, 20));
                tfTelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                panelCrearCliente.add(tfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 280, 40));

                lbEmail.setBackground(new java.awt.Color(0, 0, 0));
                lbEmail.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbEmail.setForeground(new java.awt.Color(20, 20, 20));
                lbEmail.setText("Email:");
                panelCrearCliente.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, 40));

                tfEmail.setBackground(new java.awt.Color(231, 231, 231));
                tfEmail.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfEmail.setForeground(new java.awt.Color(20, 20, 20));
                tfEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                panelCrearCliente.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 280, 40));

                lbSaldo.setBackground(new java.awt.Color(0, 0, 0));
                lbSaldo.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbSaldo.setForeground(new java.awt.Color(20, 20, 20));
                lbSaldo.setText("Saldo:");
                panelCrearCliente.add(lbSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, 40));

                tfSaldo.setBackground(new java.awt.Color(231, 231, 231));
                tfSaldo.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfSaldo.setForeground(new java.awt.Color(20, 20, 20));
                tfSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                panelCrearCliente.add(tfSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 280, 40));

                imgCrearCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/agregarUsuario.png"))); // NOI18N
                panelCrearCliente.add(imgCrearCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 40, 60));

                btnCrearCliente.setBackground(new java.awt.Color(93, 0, 0));
                btnCrearCliente.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                btnCrearCliente.setForeground(new java.awt.Color(200, 200, 200));
                btnCrearCliente.setText("      Crear Compra");
                btnCrearCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnCrearCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCrearClienteActionPerformed(evt);
                        }
                });
                panelCrearCliente.add(btnCrearCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 300, 60));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelCrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelCrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void lbBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackButtonMouseClicked
                // TODO add your handling code here:
                ClientManagementScreen cm = new ClientManagementScreen();
                cm.setVisible(true);
                this.setVisible(false);
        }//GEN-LAST:event_lbBackButtonMouseClicked

        private void btnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClienteActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_btnCrearClienteActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCrearCliente;
        private javax.swing.JLabel imgCrearCliente;
        private javax.swing.JLabel lbApellido;
        private javax.swing.JLabel lbBackButton;
        private javax.swing.JLabel lbCrearCompra;
        private javax.swing.JLabel lbEmail;
        private javax.swing.JLabel lbNombre;
        private javax.swing.JLabel lbSaldo;
        private javax.swing.JLabel lbTelefono;
        private javax.swing.JPanel pMenu;
        private javax.swing.JPanel panelCrearCliente;
        private javax.swing.JTextField tfApellido;
        private javax.swing.JTextField tfEmail;
        private javax.swing.JTextField tfNombre;
        private javax.swing.JTextField tfSaldo;
        private javax.swing.JTextField tfTelefono;
        // End of variables declaration//GEN-END:variables
}
