<<<<<<< HEAD
// cSpell:ignore metodo
=======
// cSpell:ignore metodo efecty transaccion debito credito
>>>>>>> 70a63f6aa761c84ebea74d562a15e606472b20a3
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.Gym360.view.employee;

import java.awt.Toolkit;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import main.java.com.Gym360.view.Login;
import main.java.com.Gym360.controller.Verificar;
import main.java.com.Gym360.model.classes.Cliente;
import main.java.com.Gym360.model.classes.Contabilidad;
import main.java.com.Gym360.model.classes.DetalleVenta;
import main.java.com.Gym360.model.classes.Producto;
import main.java.com.Gym360.model.classes.Transaccion;
import main.java.com.Gym360.model.classes.Venta;
import main.java.com.Gym360.model.dao.ClienteDAO;
import main.java.com.Gym360.model.dao.ContabilidadDAO;
import main.java.com.Gym360.model.dao.DetalleVentaDAO;
import main.java.com.Gym360.model.dao.ProductoDAO;
import main.java.com.Gym360.model.dao.TransaccionDAO;
import main.java.com.Gym360.model.dao.VentaDAO;
import main.java.com.Gym360.model.security.VerificarCampo;
import main.java.com.Gym360.util.dates.Dates;
import main.java.com.Gym360.util.ui.CambiarIU;
import main.java.com.Gym360.util.ui.ObtenerIU;

/**
 *
 * @author tutaa
 */
public class SalesScreen extends javax.swing.JFrame {

        /**
         * Creates new form SalesScreen
         */
        public SalesScreen() {
                initComponents();

                this.setTitle("Registrar Venta");
                this.setResizable(false);
                this.setLocationRelativeTo(null);
                this.setIconImage(Toolkit.getDefaultToolkit()
                                .getImage(getClass().getResource("/main/resources/images/logo.png")));

                ponerClientes();
                ponerProductos();
                cargarTablaVentas();

                mostrarErrores();
                btnRegistrarVenta.setEnabled(datosValidos());

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelVentas = new javax.swing.JPanel();
                pMenu = new javax.swing.JPanel();
                lbBackButton = new javax.swing.JLabel();
                lbVentas = new javax.swing.JLabel();
                lbCliente = new javax.swing.JLabel();
                cbCliente = new javax.swing.JComboBox<>();
                imgValidarCliente = new javax.swing.JLabel();
                lbProducto = new javax.swing.JLabel();
                cbProducto = new javax.swing.JComboBox<>();
                imgValidarProducto = new javax.swing.JLabel();
                lbCantidad = new javax.swing.JLabel();
                tfCantidad = new javax.swing.JTextField();
                imgValidarCantidad = new javax.swing.JLabel();
                lbPrecio = new javax.swing.JLabel();
                lbPonerPrecio = new javax.swing.JLabel();
                lbTotal = new javax.swing.JLabel();
                lbPonerTotal = new javax.swing.JLabel();
                lbMetodoPago = new javax.swing.JLabel();
                cbMetodoPago = new javax.swing.JComboBox<>();
                imgValidarMetodoPago = new javax.swing.JLabel();
                imgRegistrarVenta = new javax.swing.JLabel();
                btnRegistrarVenta = new javax.swing.JButton();
                pMedioPago = new javax.swing.JPanel();
                imgPonerMedioPago = new javax.swing.JLabel();
                spTablaVentas = new javax.swing.JScrollPane();
                tVentas = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                panelVentas.setBackground(new java.awt.Color(245, 245, 245));
                panelVentas.setMaximumSize(new java.awt.Dimension(1467, 800));
                panelVentas.setMinimumSize(new java.awt.Dimension(1467, 800));
                panelVentas.setPreferredSize(new java.awt.Dimension(1467, 800));
                panelVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                pMenu.setBackground(new java.awt.Color(93, 0, 0));
                pMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/back.png"))); // NOI18N
                lbBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbBackButtonMouseClicked(evt);
                        }
                });
                pMenu.add(lbBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

                panelVentas.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 60));

                lbVentas.setBackground(new java.awt.Color(0, 0, 0));
                lbVentas.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
                lbVentas.setForeground(new java.awt.Color(93, 0, 0));
                lbVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbVentas.setText("Ventas");
                lbVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                panelVentas.add(lbVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1470, 50));

                lbCliente.setBackground(new java.awt.Color(0, 0, 0));
                lbCliente.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbCliente.setForeground(new java.awt.Color(20, 20, 20));
                lbCliente.setText("Cliente:");
                panelVentas.add(lbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, 40));

                cbCliente.setBackground(new java.awt.Color(231, 231, 231));
                cbCliente.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                cbCliente.setForeground(new java.awt.Color(20, 20, 20));
                cbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                cbCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbClienteActionPerformed(evt);
                        }
                });
                panelVentas.add(cbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 280, 40));

                imgValidarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelVentas.add(imgValidarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, -1, -1));

                lbProducto.setBackground(new java.awt.Color(0, 0, 0));
                lbProducto.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbProducto.setForeground(new java.awt.Color(20, 20, 20));
                lbProducto.setText("Producto:");
                panelVentas.add(lbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, 40));

                cbProducto.setBackground(new java.awt.Color(231, 231, 231));
                cbProducto.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                cbProducto.setForeground(new java.awt.Color(20, 20, 20));
                cbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                cbProducto.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbProductoActionPerformed(evt);
                        }
                });
                panelVentas.add(cbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 280, 40));

                imgValidarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelVentas.add(imgValidarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));

                lbCantidad.setBackground(new java.awt.Color(0, 0, 0));
                lbCantidad.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbCantidad.setForeground(new java.awt.Color(20, 20, 20));
                lbCantidad.setText("Cantidad:");
                panelVentas.add(lbCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, 40));

                tfCantidad.setBackground(new java.awt.Color(231, 231, 231));
                tfCantidad.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfCantidad.setForeground(new java.awt.Color(20, 20, 20));
                tfCantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                tfCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfCantidadKeyReleased(evt);
                        }
                });
                panelVentas.add(tfCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 280, 40));

                imgValidarCantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelVentas.add(imgValidarCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

                lbPrecio.setBackground(new java.awt.Color(0, 0, 0));
                lbPrecio.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbPrecio.setForeground(new java.awt.Color(20, 20, 20));
                lbPrecio.setText("Precio unitario:");
                panelVentas.add(lbPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, 40));

                lbPonerPrecio.setBackground(new java.awt.Color(0, 0, 0));
                lbPonerPrecio.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbPonerPrecio.setForeground(new java.awt.Color(20, 20, 20));
                lbPonerPrecio.setText("0");
                panelVentas.add(lbPonerPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 280, 40));

                lbTotal.setBackground(new java.awt.Color(0, 0, 0));
                lbTotal.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbTotal.setForeground(new java.awt.Color(20, 20, 20));
                lbTotal.setText("Total:");
                panelVentas.add(lbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, 40));

                lbPonerTotal.setBackground(new java.awt.Color(0, 0, 0));
                lbPonerTotal.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbPonerTotal.setForeground(new java.awt.Color(20, 20, 20));
                lbPonerTotal.setText("0");
                panelVentas.add(lbPonerTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 280, 40));

                lbMetodoPago.setBackground(new java.awt.Color(0, 0, 0));
                lbMetodoPago.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbMetodoPago.setForeground(new java.awt.Color(20, 20, 20));
                lbMetodoPago.setText("Método de Pago:");
                panelVentas.add(lbMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, 40));

                cbMetodoPago.setBackground(new java.awt.Color(231, 231, 231));
                cbMetodoPago.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                cbMetodoPago.setForeground(new java.awt.Color(20, 20, 20));
                cbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Efectivo", "Tarjeta Débito", "Tarjeta Crédito", "PSE", "Efecty" }));
                cbMetodoPago.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbMetodoPagoActionPerformed(evt);
                        }
                });
                panelVentas.add(cbMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 280, 40));

                imgValidarMetodoPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelVentas.add(imgValidarMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, -1, -1));

                imgRegistrarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/confirmarAsistencia.png"))); // NOI18N
                panelVentas.add(imgRegistrarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 660, -1, 60));

                btnRegistrarVenta.setBackground(new java.awt.Color(93, 0, 0));
                btnRegistrarVenta.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                btnRegistrarVenta.setForeground(new java.awt.Color(200, 200, 200));
                btnRegistrarVenta.setText("      Registrar Venta");
                btnRegistrarVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRegistrarVentaActionPerformed(evt);
                        }
                });
                panelVentas.add(btnRegistrarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 660, 360, 60));

                pMedioPago.setBackground(new java.awt.Color(245, 245, 245));
                pMedioPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
                pMedioPago.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                pMedioPago.add(imgPonerMedioPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

                panelVentas.add(pMedioPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 90, 80));

                tVentas.setBackground(new java.awt.Color(232, 232, 232));
                tVentas.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tVentas.setForeground(new java.awt.Color(20, 20, 20));
                tVentas.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {"Juan Pérez", "juan@email.com", " Administrador", "Activo"},
                                {"María López ", "maria@email.com", "Empleado", "Inactivo"},
                                {"Carlos Ruiz", "carlos@email.com", "Cliente", "Activo"},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Nombre", "Correo", "Rol", "Estado"
                        }
                ));
                tVentas.setShowGrid(false);
                tVentas.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tVentasMouseClicked(evt);
                        }
                });
                spTablaVentas.setViewportView(tVentas);

                panelVentas.add(spTablaVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 550, 500));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
=======
        private void tVentasMouseClicked(java.awt.event.MouseEvent evt) {

        }

        public void cargarTablaVentas() {
                VentaDAO ventaDAO = new VentaDAO();
                List<Venta> ventas = ventaDAO.obtenerTodos();

                // Actualizado las columnas eliminando "ID Venta" ya que ahora idEmpleado es
                // la PK
                String[] columnas = { "ID Venta", "Fecha", "Total", "idEmpleado", "idCliente" };
                DefaultTableModel model = new DefaultTableModel(columnas, 0);

                for (Venta venta : ventas) {
                        // Removido venta.getIdVenta() ya que ese campo ya no existe
                        Object[] fila = { venta.getIdVenta(), venta.getFecha(), venta.getTotal(), venta.getIdEmpleado(),
                                        venta.getIdClienteProveedor() };
                        model.addRow(fila);
                }

                tVentas.setModel(model); // Asegúrate de que esta tabla exista en tu clase
        }

        private void cbMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {
                ponerImagenMetodoPago();
                mostrarErrores();
                btnRegistrarVenta.setEnabled(datosValidos());
        }

        private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {
                mostrarErrores();
                btnRegistrarVenta.setEnabled(datosValidos());
        }

        private void tfCantidadKeyReleased(java.awt.event.KeyEvent evt) {
                mostrarErrores();
                ponerTotal();
                btnRegistrarVenta.setEnabled(datosValidos());
        }

        private void cbProductoActionPerformed(java.awt.event.ActionEvent evt) {
                ponerPrecioUnitario();
                ponerTotal();
                mostrarErrores();
                btnRegistrarVenta.setEnabled(datosValidos());

        }

>>>>>>> 70a63f6aa761c84ebea74d562a15e606472b20a3
        private void lbBackButtonMouseClicked(java.awt.event.MouseEvent evt) {
                DashboardEmployeeScreen de = new DashboardEmployeeScreen();
                de.setVisible(true);
                this.setVisible(false);
        }

        private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {
<<<<<<< HEAD

=======
                registrarVenta();
        }

        private void registrarVenta() {

                try {
                        String[] datosProductoSeleccionado = ObtenerIU.obtenerSeleccionCombo(cbProducto).split("-");
                        String[] datosClienteSeleccionado = ObtenerIU.obtenerSeleccionCombo(cbCliente).split("-");

                        int idProducto = Integer.parseInt(datosProductoSeleccionado[0].trim());
                        int idCliente = Integer.parseInt(datosClienteSeleccionado[0].trim());

                        String fecha = Dates.obtenerFechaHoy();

                        double total = Double.parseDouble(ObtenerIU.obtenerTextoEtiqueta(lbPonerTotal));

                        VentaDAO ventaDao = new VentaDAO();
                        Venta venta = new Venta(0, fecha, total, Integer.parseInt(Login.idGuardar), idCliente);
                        ventaDao.insertar(venta);

                        var ventas = ventaDao.obtenerTodos();

                        var ultimaVenta = ventas.get(ventas.size() - 1);

                        DetalleVentaDAO detalleComDao = new DetalleVentaDAO();

                        DetalleVenta detalleCom = new DetalleVenta(0, ultimaVenta.getIdVenta(), idProducto);
                        detalleComDao.insertar(detalleCom);

                        // Contabilidad
                        ContabilidadDAO contDao = new ContabilidadDAO();
                        Contabilidad cont = new Contabilidad(0, total, 0);
                        contDao.insertar(cont);
                        // Transacción
                        var movimientos = contDao.obtenerTodos();

                        var ultimoMovimiento = movimientos.get(movimientos.size() - 1);

                        TransaccionDAO transDao = new TransaccionDAO();
                        Transaccion nuevaTransaccion = new Transaccion(0, ultimoMovimiento.getIdContabilidad(),
                                        String.format("Venta de %s por el total de $%.2f",
                                                        datosProductoSeleccionado[1].trim(), total));
                        transDao.insertar(nuevaTransaccion);

                        JOptionPane.showMessageDialog(this, "La compra se registró correctamente.",
                                        "Actualización exitosa", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar la Compra." + e.toString(),
                                        "Error", JOptionPane.ERROR_MESSAGE);
                }

        }

        private void ponerPrecioUnitario() {
                ObtenerIU.obtenerSeleccionCombo(cbProducto);
                try {

                        String[] datosProductoSeleccionado = ObtenerIU.obtenerSeleccionCombo(cbProducto).split("-");

                        int idProducto = Integer.parseInt(datosProductoSeleccionado[0].trim());

                        ProductoDAO productoDAO = new ProductoDAO();
                        Producto producto = productoDAO.obtenerPorId(idProducto);

                        CambiarIU.ponerTextoEtiqueta(lbPonerPrecio, String.valueOf(producto.getPrecioUnitario()));
                } catch (Exception e) {
                }
                {
                }

        }

        private void ponerTotal() {
                String cantidadStr = ObtenerIU.obtenerTextoCampo(tfCantidad).trim();
                String precioStr = ObtenerIU.obtenerTextoEtiqueta(lbPonerPrecio).trim();

                if (!cantidadStr.isEmpty() && !precioStr.isEmpty()) {
                        try {
                                double cantidad = Double.parseDouble(cantidadStr);
                                double precio = Double.parseDouble(precioStr);
                                double total = cantidad * precio;
                                CambiarIU.ponerTextoEtiqueta(lbPonerTotal, String.valueOf(total));
                        } catch (NumberFormatException e) {

                                CambiarIU.ponerTextoEtiqueta(lbPonerTotal, "Error: valor no numérico");
                        }
                } else {
                        CambiarIU.ponerTextoEtiqueta(lbPonerTotal, "Error: campo vacío");
                }

        }

        private void ponerClientes() {
                ClienteDAO clienteDAO = new ClienteDAO();

                List<Cliente> clientes = clienteDAO.obtenerTodos();

                CambiarIU.vaciarCombo(cbCliente);
                for (Cliente p : clientes) {
                        cbCliente.addItem(String.format("%s - %s", p.getId(), p.getNombre()));

                }
        }

        private void ponerImagenMetodoPago() {
                if (ObtenerIU.obtenerIndiceSeleccionCombo(cbMetodoPago) == 1) {
                        new CambiarIU().setImageLabel(imgPonerMedioPago, "/main/resources/images/efectivo.jpg");

                } else if (ObtenerIU.obtenerIndiceSeleccionCombo(cbMetodoPago) == 2) {
                        new CambiarIU().setImageLabel(imgPonerMedioPago, "/main/resources/images/debito.png");

                } else if (ObtenerIU.obtenerIndiceSeleccionCombo(cbMetodoPago) == 3) {
                        new CambiarIU().setImageLabel(imgPonerMedioPago, "/main/resources/images/credito.png");

                } else if (ObtenerIU.obtenerIndiceSeleccionCombo(cbMetodoPago) == 4) {
                        new CambiarIU().setImageLabel(imgPonerMedioPago, "/main/resources/images/pse.jpg");

                } else if (ObtenerIU.obtenerIndiceSeleccionCombo(cbMetodoPago) == 5) {
                        new CambiarIU().setImageLabel(imgPonerMedioPago, "/main/resources/images/efecty.png");

                } else {
                        imgPonerMedioPago.setIcon(null);
                }

        }

        private void ponerProductos() {
                ProductoDAO productoDAO = new ProductoDAO();

                List<Producto> productos = productoDAO.obtenerTodos();

                CambiarIU.vaciarCombo(cbProducto);
                for (Producto p : productos) {
                        cbProducto.addItem(String.format("%d - %s", p.getIdProducto(), p.getNombre()));

                }
        }

        private boolean datosValidos() {
                return Verificar.validarStock((ObtenerIU.obtenerTextoCampo(tfCantidad)))
                                && Verificar.validarComboBox(ObtenerIU.obtenerSeleccionCombo(cbProducto))
                                && Verificar.validarComboBox(ObtenerIU.obtenerSeleccionCombo(cbCliente))
                                && Verificar.validarComboBox(ObtenerIU.obtenerSeleccionCombo(cbMetodoPago));
        }

        private void mostrarErrores() {
                // tfCantidad
                VerificarCampo.verificarCampo(Verificar.validarStock(ObtenerIU.obtenerTextoCampo(tfCantidad)),
                                imgValidarCantidad, "La cantidad es válida.", "La cantidad no es válida.");

                // cbProducto
                VerificarCampo.verificarCampo(Verificar.validarComboBox(ObtenerIU.obtenerSeleccionCombo(cbProducto)),
                                imgValidarProducto, "Ha seleccionado un producto.", "Debe seleccionar un producto.");

                // cbCliente
                VerificarCampo.verificarCampo(Verificar.validarComboBox(ObtenerIU.obtenerSeleccionCombo(cbCliente)),
                                imgValidarCliente, "Ha seleccionado un cliente.", "Debe seleccionar un cliente.");

                // cbMetodoPago
                VerificarCampo.verificarCampo(Verificar.validarComboBox(ObtenerIU.obtenerSeleccionCombo(cbMetodoPago)),
                                imgValidarMetodoPago, "Ha seleccionado un método de pago.",
                                "Debe seleccionar un método de pago.");

>>>>>>> 70a63f6aa761c84ebea74d562a15e606472b20a3
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnRegistrarVenta;
        private javax.swing.JComboBox<String> cbCliente;
        private javax.swing.JComboBox<String> cbMetodoPago;
        private javax.swing.JComboBox<String> cbProducto;
        private javax.swing.JLabel imgPonerMedioPago;
        private javax.swing.JLabel imgRegistrarVenta;
        private javax.swing.JLabel imgValidarCantidad;
        private javax.swing.JLabel imgValidarCliente;
        private javax.swing.JLabel imgValidarMetodoPago;
        private javax.swing.JLabel imgValidarProducto;
        private javax.swing.JLabel lbBackButton;
        private javax.swing.JLabel lbCantidad;
        private javax.swing.JLabel lbCliente;
        private javax.swing.JLabel lbMetodoPago;
        private javax.swing.JLabel lbPonerPrecio;
        private javax.swing.JLabel lbPonerTotal;
        private javax.swing.JLabel lbPrecio;
        private javax.swing.JLabel lbProducto;
        private javax.swing.JLabel lbTotal;
        private javax.swing.JLabel lbVentas;
        private javax.swing.JPanel pMedioPago;
        private javax.swing.JPanel pMenu;
        private javax.swing.JPanel panelVentas;
        private javax.swing.JScrollPane spTablaVentas;
        private javax.swing.JTable tVentas;
        private javax.swing.JTextField tfCantidad;
        // End of variables declaration//GEN-END:variables
}
