/*
cSpell:ignore identificacion telefono
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.Gym360.view.admin.payroll;

import java.awt.Toolkit;

import javax.swing.JOptionPane;

import main.java.com.Gym360.controller.Verificar;
import main.java.com.Gym360.model.classes.Empleado;
import main.java.com.Gym360.model.classes.Nomina;
import main.java.com.Gym360.model.dao.EmpleadoDAO;
import main.java.com.Gym360.model.dao.NominaDAO;
import main.java.com.Gym360.model.security.VerificarCampo;
import main.java.com.Gym360.util.ui.ObtenerIU;

/**
 *
 * @author tutaa
 */
public class CreateEmployee extends javax.swing.JFrame {

        /**
         * Creates new form ManageUsersScreen
         */
        public CreateEmployee() {
                initComponents();
                this.setTitle("Registrar Empleado");
                this.setResizable(false);
                this.setLocationRelativeTo(null);
                this.setIconImage(Toolkit.getDefaultToolkit()
                                .getImage(getClass().getResource("/main/resources/images/logo.png")));

                btnCrearEmpleado.setEnabled(datosValidos());
                mostrarErrores();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelEditarEmpleado = new javax.swing.JPanel();
                pMenu = new javax.swing.JPanel();
                lbBackButton = new javax.swing.JLabel();
                lbCrearUsuario = new javax.swing.JLabel();
                lbIdentificacion = new javax.swing.JLabel();
                tfIdentificacion = new javax.swing.JTextField();
                imgValidarIdentificacion = new javax.swing.JLabel();
                lbNombre = new javax.swing.JLabel();
                tfNombre = new javax.swing.JTextField();
                imgValidarNombre = new javax.swing.JLabel();
                lbApellido = new javax.swing.JLabel();
                tfApellido = new javax.swing.JTextField();
                imgValidarApellido = new javax.swing.JLabel();
                lbCorreo = new javax.swing.JLabel();
                tfCorreo = new javax.swing.JTextField();
                imgValidarCorreo = new javax.swing.JLabel();
                lbCargo = new javax.swing.JLabel();
                cbCargo = new javax.swing.JComboBox<>();
                imgValidarCargo = new javax.swing.JLabel();
                lbTelefono = new javax.swing.JLabel();
                tfTelefono = new javax.swing.JTextField();
                imgValidarTelefono = new javax.swing.JLabel();
                lbSalario = new javax.swing.JLabel();
                tfSalario = new javax.swing.JTextField();
                imgValidarSalario = new javax.swing.JLabel();
                lbFechaContrato = new javax.swing.JLabel();
                tfFechaContrato = new javax.swing.JTextField();
                imgValidarFechaContrato = new javax.swing.JLabel();
                imgCrearEmpleado = new javax.swing.JLabel();
                btnCrearEmpleado = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                panelEditarEmpleado.setBackground(new java.awt.Color(245, 245, 245));
                panelEditarEmpleado.setMaximumSize(new java.awt.Dimension(1467, 800));
                panelEditarEmpleado.setMinimumSize(new java.awt.Dimension(1467, 800));
                panelEditarEmpleado.setPreferredSize(new java.awt.Dimension(1467, 800));
                panelEditarEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                pMenu.setBackground(new java.awt.Color(93, 0, 0));
                pMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbBackButton.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/back.png"))); // NOI18N
                lbBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbBackButtonMouseClicked(evt);
                        }
                });
                pMenu.add(lbBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

                lbCrearUsuario.setBackground(new java.awt.Color(0, 0, 0));
                lbCrearUsuario.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
                lbCrearUsuario.setForeground(new java.awt.Color(245, 245, 245));
                lbCrearUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbCrearUsuario.setText("REGISTRAR EMPLEADO");
                lbCrearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                pMenu.add(lbCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

                panelEditarEmpleado.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

                lbIdentificacion.setBackground(new java.awt.Color(0, 0, 0));
                lbIdentificacion.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbIdentificacion.setForeground(new java.awt.Color(20, 20, 20));
                lbIdentificacion.setText("Identificación:");
                panelEditarEmpleado.add(lbIdentificacion,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 40));

                tfIdentificacion.setBackground(new java.awt.Color(231, 231, 231));
                tfIdentificacion.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfIdentificacion.setForeground(new java.awt.Color(20, 20, 20));
                tfIdentificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                tfIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfIdentificacionKeyReleased(evt);
                        }
                });
                panelEditarEmpleado.add(tfIdentificacion,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 280, 40));

                imgValidarIdentificacion.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelEditarEmpleado.add(imgValidarIdentificacion,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 30, 30));

                lbNombre.setBackground(new java.awt.Color(0, 0, 0));
                lbNombre.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbNombre.setForeground(new java.awt.Color(20, 20, 20));
                lbNombre.setText("Nombre:");
                panelEditarEmpleado.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 40));

                tfNombre.setBackground(new java.awt.Color(231, 231, 231));
                tfNombre.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfNombre.setForeground(new java.awt.Color(20, 20, 20));
                tfNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfNombreKeyReleased(evt);
                        }
                });
                panelEditarEmpleado.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 280, 40));

                imgValidarNombre.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelEditarEmpleado.add(imgValidarNombre,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 30, 30));

                lbApellido.setBackground(new java.awt.Color(0, 0, 0));
                lbApellido.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbApellido.setForeground(new java.awt.Color(20, 20, 20));
                lbApellido.setText("Apellido:");
                panelEditarEmpleado.add(lbApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 40));

                tfApellido.setBackground(new java.awt.Color(231, 231, 231));
                tfApellido.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfApellido.setForeground(new java.awt.Color(20, 20, 20));
                tfApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                tfApellido.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfApellidoKeyReleased(evt);
                        }
                });
                panelEditarEmpleado.add(tfApellido,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 280, 40));

                imgValidarApellido.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelEditarEmpleado.add(imgValidarApellido,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 30, 30));

                lbCorreo.setBackground(new java.awt.Color(0, 0, 0));
                lbCorreo.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbCorreo.setForeground(new java.awt.Color(20, 20, 20));
                lbCorreo.setText("Correo:");
                panelEditarEmpleado.add(lbCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, 40));

                tfCorreo.setBackground(new java.awt.Color(231, 231, 231));
                tfCorreo.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfCorreo.setForeground(new java.awt.Color(20, 20, 20));
                tfCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                tfCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfCorreoKeyReleased(evt);
                        }
                });
                panelEditarEmpleado.add(tfCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 280, 40));

                imgValidarCorreo.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelEditarEmpleado.add(imgValidarCorreo,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 30, 30));

                lbCargo.setBackground(new java.awt.Color(0, 0, 0));
                lbCargo.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbCargo.setForeground(new java.awt.Color(20, 20, 20));
                lbCargo.setText("Cargo:");
                panelEditarEmpleado.add(lbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, 40));

                cbCargo.setBackground(new java.awt.Color(231, 231, 231));
                cbCargo.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                cbCargo.setForeground(new java.awt.Color(20, 20, 20));
                cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Seleccionar", "Admin", "Empleado", "Cliente" }));
                cbCargo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbCargoActionPerformed(evt);
                        }
                });
                panelEditarEmpleado.add(cbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 280, 40));

                imgValidarCargo.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelEditarEmpleado.add(imgValidarCargo,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 30, 30));

                lbTelefono.setBackground(new java.awt.Color(0, 0, 0));
                lbTelefono.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbTelefono.setForeground(new java.awt.Color(20, 20, 20));
                lbTelefono.setText("Teléfono:");
                panelEditarEmpleado.add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, 40));

                tfTelefono.setBackground(new java.awt.Color(231, 231, 231));
                tfTelefono.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfTelefono.setForeground(new java.awt.Color(20, 20, 20));
                tfTelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                tfTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfTelefonoKeyReleased(evt);
                        }
                });
                panelEditarEmpleado.add(tfTelefono,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 280, 40));

                imgValidarTelefono.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelEditarEmpleado.add(imgValidarTelefono,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 30, 30));

                lbSalario.setBackground(new java.awt.Color(0, 0, 0));
                lbSalario.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbSalario.setForeground(new java.awt.Color(20, 20, 20));
                lbSalario.setText("Salario:");
                panelEditarEmpleado.add(lbSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, 40));

                tfSalario.setBackground(new java.awt.Color(231, 231, 231));
                tfSalario.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfSalario.setForeground(new java.awt.Color(20, 20, 20));
                tfSalario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                tfSalario.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfSalarioKeyReleased(evt);
                        }
                });
                panelEditarEmpleado.add(tfSalario,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 280, 40));

                imgValidarSalario.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelEditarEmpleado.add(imgValidarSalario,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 30, 30));

                lbFechaContrato.setBackground(new java.awt.Color(0, 0, 0));
                lbFechaContrato.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbFechaContrato.setForeground(new java.awt.Color(20, 20, 20));
                lbFechaContrato.setText("Fecha Contrato:");
                panelEditarEmpleado.add(lbFechaContrato,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, -1, 40));

                tfFechaContrato.setBackground(new java.awt.Color(231, 231, 231));
                tfFechaContrato.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfFechaContrato.setForeground(new java.awt.Color(20, 20, 20));
                tfFechaContrato.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                tfFechaContrato.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfFechaContratoKeyReleased(evt);
                        }
                });
                panelEditarEmpleado.add(tfFechaContrato,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 590, 280, 40));

                imgValidarFechaContrato.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelEditarEmpleado.add(imgValidarFechaContrato,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 30, 30));

                imgCrearEmpleado.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/main/resources/images/agregarUsuario.png"))); // NOI18N
                panelEditarEmpleado.add(imgCrearEmpleado,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 660, 40, 60));

                btnCrearEmpleado.setBackground(new java.awt.Color(93, 0, 0));
                btnCrearEmpleado.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                btnCrearEmpleado.setForeground(new java.awt.Color(200, 200, 200));
                btnCrearEmpleado.setText("      Registrar Empleado");
                btnCrearEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnCrearEmpleado.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCrearEmpleadoActionPerformed(evt);
                        }
                });
                panelEditarEmpleado.add(btnCrearEmpleado,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 300, 60));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelEditarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 675,
                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelEditarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 749,
                                                Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void tfApellidoKeyReleased(java.awt.event.KeyEvent evt) {
                btnCrearEmpleado.setEnabled(datosValidos());
                mostrarErrores();
        }

        private void tfSalarioKeyReleased(java.awt.event.KeyEvent evt) {
                btnCrearEmpleado.setEnabled(datosValidos());
                mostrarErrores();
        }

        private void tfFechaContratoKeyReleased(java.awt.event.KeyEvent evt) {
                btnCrearEmpleado.setEnabled(datosValidos());
                mostrarErrores();
        }

        private void tfIdentificacionKeyReleased(java.awt.event.KeyEvent evt) {
                btnCrearEmpleado.setEnabled(datosValidos());
                mostrarErrores();
        }

        private void tfNombreKeyReleased(java.awt.event.KeyEvent evt) {
                btnCrearEmpleado.setEnabled(datosValidos());
                mostrarErrores();
        }

        private void tfCorreoKeyReleased(java.awt.event.KeyEvent evt) {
                btnCrearEmpleado.setEnabled(datosValidos());
                mostrarErrores();
        }

        private void tfTelefonoKeyReleased(java.awt.event.KeyEvent evt) {
                btnCrearEmpleado.setEnabled(datosValidos());
                mostrarErrores();
        }

        private void cbCargoActionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEmpleado.setEnabled(datosValidos());
                mostrarErrores();
        }

        private void btnCrearEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {
                crearEmpleado();
        }

        private void lbBackButtonMouseClicked(java.awt.event.MouseEvent evt) {

                PayrollManagementScreen pm = new PayrollManagementScreen();
                pm.setVisible(true);
                this.setVisible(false);
        }

        private void crearEmpleado() {
                EmpleadoDAO empleadoDAO = new EmpleadoDAO();
                NominaDAO nominaDAO = new NominaDAO();

                try {
                        // Obtener datos desde los campos del formulario
                        int idEmpleado = Integer.parseInt(ObtenerIU.obtenerTextoCampo(tfIdentificacion));
                        String nombre = ObtenerIU.obtenerTextoCampo(tfNombre);
                        String apellido = ObtenerIU.obtenerTextoCampo(tfApellido);
                        double salario = Double.parseDouble(ObtenerIU.obtenerTextoCampo(tfSalario));
                        String fechaContratacion = ObtenerIU.obtenerTextoCampo(tfFechaContrato);
                        String cargo = ObtenerIU.obtenerSeleccionCombo(cbCargo);
                        String telefono = ObtenerIU.obtenerTextoCampo(tfTelefono);
                        String email = ObtenerIU.obtenerTextoCampo(tfCorreo);

                        // Crear objeto Empleado con los datos actualizados
                        Empleado empleado = new Empleado();
                        empleado.setIdEmpleado(idEmpleado);
                        empleado.setNombre(nombre);
                        empleado.setApellido(apellido);
                        empleado.setSalario(salario);
                        empleado.setFechaContratacion(fechaContratacion);
                        empleado.setCargo(cargo);
                        empleado.setTelefono(telefono);
                        empleado.setEmail(email);

                        // Insertar el empleado en la base de datos
                        boolean resultadoEmpleado = empleadoDAO.insertar(empleado);

                        if (resultadoEmpleado) {
                                // Crear un registro inicial en la tabla Nomina
                                Nomina nomina = new Nomina();
                                                                          // Colombia - ajustar según sea necesario

                                // Configurar la nómina con valores predeterminados
                                nomina.setFecha(fechaContratacion); // Usar la misma fecha de contratación
                                nomina.setSalarioBase(salario);
                                nomina.setDeducciones(0.0);
                                nomina.setBonificaciones(0.0);
                                nomina.setIdEmpleado(idEmpleado);

                                // Insertar la nómina en la base de datos
                                boolean resultadoNomina = nominaDAO.insertar(nomina);

                                if (resultadoNomina) {
                                        JOptionPane.showMessageDialog(this,
                                                        "El empleado se registró correctamente y se creó su registro de nómina inicial.",
                                                        "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
                                } else {
                                        JOptionPane.showMessageDialog(this,
                                                        "El empleado se registró, pero no se pudo crear su registro de nómina inicial.",
                                                        "Advertencia", JOptionPane.WARNING_MESSAGE);
                                }

                                // Redirigir o refrescar vista
                                PayrollManagementScreen mu = new PayrollManagementScreen();
                                mu.setVisible(true);
                                this.setVisible(false);
                        } else {
                                JOptionPane.showMessageDialog(this, "No se pudo registrar el empleado.", "Error",
                                                JOptionPane.ERROR_MESSAGE);
                        }

                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this,
                                        "Ocurrió un error al registrar el empleado: " + e.getMessage(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }

        private boolean datosValidos() {
                return Verificar.validarNombre(ObtenerIU.obtenerTextoCampo(tfNombre))
                                && Verificar.validarNombre(ObtenerIU.obtenerTextoCampo(tfApellido))
                                && Verificar.validarYVerificarCedulaEmpleado(
                                                ObtenerIU.obtenerTextoCampo(tfIdentificacion))

                                && Verificar.validarCorreo(ObtenerIU.obtenerTextoCampo(tfCorreo))
                                && Verificar.validarComboBox((ObtenerIU.obtenerSeleccionCombo(cbCargo)))
                                && Verificar.validarSalario(ObtenerIU.obtenerTextoCampo(tfSalario))
                                && Verificar.validarFechaMenorIgualHoy(ObtenerIU.obtenerTextoCampo(tfFechaContrato))
                                && Verificar.validarTelefono((ObtenerIU.obtenerTextoCampo(tfTelefono)));

        }

        private void mostrarErrores() {
                // tfNombre
                VerificarCampo.verificarCampo(Verificar.validarNombre(ObtenerIU.obtenerTextoCampo(tfNombre)),
                                imgValidarNombre, "El nombre es válido.", "El nombre no es válido.");

                // tfApellido
                VerificarCampo.verificarCampo(Verificar.validarNombre(ObtenerIU.obtenerTextoCampo(tfApellido)),
                                imgValidarApellido, "El apellido es válido.", "El apellido no es válido.");

                // tfIdentificacion
                VerificarCampo.verificarCampo(
                                Verificar.validarYVerificarCedulaEmpleado(
                                                ObtenerIU.obtenerTextoCampo(tfIdentificacion)),
                                imgValidarIdentificacion, "La identificación es válida.",
                                "La identificación no es válida.");

                // tfCorreo
                VerificarCampo.verificarCampo(Verificar.validarCorreo(ObtenerIU.obtenerTextoCampo(tfCorreo)),
                                imgValidarCorreo, "El correo es válido.", "El correo no es válido.");

                // tfTelefono
                VerificarCampo.verificarCampo(Verificar.validarTelefono(ObtenerIU.obtenerTextoCampo(tfTelefono)),
                                imgValidarTelefono, "El teléfono es válido.", "El teléfono no es válido.");

                // cbCargo
                VerificarCampo.verificarCampo(Verificar.validarComboBox(ObtenerIU.obtenerSeleccionCombo(cbCargo)),
                                imgValidarCargo, "Ha seleccionado un cargo.", "Debe seleccionar un cargo.");

                // tfSalario
                VerificarCampo.verificarCampo(Verificar.validarSalario(ObtenerIU.obtenerTextoCampo(tfSalario)),
                                imgValidarSalario, "El salario es válido.", "El salario no es válido.");

                // tfFechaContrato
                VerificarCampo.verificarCampo(
                                Verificar.validarFechaMenorIgualHoy(ObtenerIU.obtenerTextoCampo(tfFechaContrato)),
                                imgValidarFechaContrato, "La fecha de contrato es válida.",
                                "La fecha de contrato no es válida.");
        }

        /**
         * @param args the command line arguments
         */

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCrearEmpleado;
        private javax.swing.JComboBox<String> cbCargo;
        private javax.swing.JLabel imgCrearEmpleado;
        private javax.swing.JLabel imgValidarApellido;
        private javax.swing.JLabel imgValidarCargo;
        private javax.swing.JLabel imgValidarCorreo;
        private javax.swing.JLabel imgValidarFechaContrato;
        private javax.swing.JLabel imgValidarIdentificacion;
        private javax.swing.JLabel imgValidarNombre;
        private javax.swing.JLabel imgValidarSalario;
        private javax.swing.JLabel imgValidarTelefono;
        private javax.swing.JLabel lbApellido;
        private javax.swing.JLabel lbBackButton;
        private javax.swing.JLabel lbCargo;
        private javax.swing.JLabel lbCorreo;
        private javax.swing.JLabel lbCrearUsuario;
        private javax.swing.JLabel lbFechaContrato;
        private javax.swing.JLabel lbIdentificacion;
        private javax.swing.JLabel lbNombre;
        private javax.swing.JLabel lbSalario;
        private javax.swing.JLabel lbTelefono;
        private javax.swing.JPanel pMenu;
        private javax.swing.JPanel panelEditarEmpleado;
        private javax.swing.JTextField tfApellido;
        private javax.swing.JTextField tfCorreo;
        private javax.swing.JTextField tfFechaContrato;
        private javax.swing.JTextField tfIdentificacion;
        private javax.swing.JTextField tfNombre;
        private javax.swing.JTextField tfSalario;
        private javax.swing.JTextField tfTelefono;
        // End of variables declaration//GEN-END:variables
}
