/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.Gym360.view.admin.payroll;

import main.java.com.Gym360.view.admin.inventory.*;
import main.java.com.Gym360.view.admin.users.*;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.EventQueue;
import java.awt.Toolkit;
import javax.swing.UIManager;

/**
 *
 * @author tutaa
 */
public class HistoryPayroll extends javax.swing.JFrame {

	/**
	 * Creates new form ManageUsersScreen
	 */
	public HistoryPayroll() {
		initComponents();
		this.setTitle("Historial de Pagos");
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/main/resources/images/logo.png")));
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelHistoryPayroll = new javax.swing.JPanel();
                pMenu = new javax.swing.JPanel();
                lbBackButton = new javax.swing.JLabel();
                lbHistorialPagos = new javax.swing.JLabel();
                spTablaHistorialPagos = new javax.swing.JScrollPane();
                tTablaHistorialPagos = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                panelHistoryPayroll.setBackground(new java.awt.Color(245, 245, 245));
                panelHistoryPayroll.setMaximumSize(new java.awt.Dimension(1467, 800));
                panelHistoryPayroll.setMinimumSize(new java.awt.Dimension(1467, 800));
                panelHistoryPayroll.setPreferredSize(new java.awt.Dimension(1467, 800));
                panelHistoryPayroll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                pMenu.setBackground(new java.awt.Color(93, 0, 0));
                pMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/back.png"))); // NOI18N
                lbBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbBackButtonMouseClicked(evt);
                        }
                });
                pMenu.add(lbBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

                lbHistorialPagos.setBackground(new java.awt.Color(0, 0, 0));
                lbHistorialPagos.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
                lbHistorialPagos.setForeground(new java.awt.Color(245, 245, 245));
                lbHistorialPagos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbHistorialPagos.setText("Historial de Pagos");
                lbHistorialPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                pMenu.add(lbHistorialPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

                panelHistoryPayroll.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

                tTablaHistorialPagos.setBackground(new java.awt.Color(232, 232, 232));
                tTablaHistorialPagos.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tTablaHistorialPagos.setForeground(new java.awt.Color(20, 20, 20));
                tTablaHistorialPagos.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {"Juan Pérez", "juan@email.com", " Administrador", "Activo"},
                                {"María López ", "maria@email.com", "Empleado", "Inactivo"},
                                {"Carlos Ruiz", "carlos@email.com", "Cliente", "Activo"},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Nombre", "Correo", "Rol", "Estado"
                        }
                ));
                tTablaHistorialPagos.setShowGrid(false);
                spTablaHistorialPagos.setViewportView(tTablaHistorialPagos);

                panelHistoryPayroll.add(spTablaHistorialPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 500, 620));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelHistoryPayroll, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelHistoryPayroll, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void lbBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackButtonMouseClicked
		PayrollManagementScreen pm = new PayrollManagementScreen();
		pm.setVisible(true);
		this.setVisible(false);
        }//GEN-LAST:event_lbBackButtonMouseClicked


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel lbBackButton;
        private javax.swing.JLabel lbHistorialPagos;
        private javax.swing.JPanel pMenu;
        private javax.swing.JPanel panelHistoryPayroll;
        private javax.swing.JScrollPane spTablaHistorialPagos;
        private javax.swing.JTable tTablaHistorialPagos;
        // End of variables declaration//GEN-END:variables
}
