/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.Gym360.view.admin.payroll;

import java.awt.Toolkit;
import main.java.com.Gym360.view.admin.DashboardAdminScreen;

/**
 *
 * @author tutaa
 */
public class PayrollManagementScreen extends javax.swing.JFrame {

	/**
	 * Creates new form PayrollManagementScreen
	 */
	public PayrollManagementScreen() {
		initComponents();
		this.setTitle("Gestión de Nómina");
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/main/resources/images/logo.png")));
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelPayrollManagement = new javax.swing.JPanel();
                pMenu = new javax.swing.JPanel();
                lbBackButton = new javax.swing.JLabel();
                lbBuscar = new javax.swing.JLabel();
                tfBuscar = new javax.swing.JTextField();
                lbEmpleados = new javax.swing.JLabel();
                spTablaEmpleadosNomina = new javax.swing.JScrollPane();
                tTablaEmpleadosNomina = new javax.swing.JTable();
                imgCalcularNomina = new javax.swing.JLabel();
                btnCalcularNomina = new javax.swing.JButton();
                imgHistorialPagos = new javax.swing.JLabel();
                btnHistorialPagos = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                panelPayrollManagement.setBackground(new java.awt.Color(245, 245, 245));
                panelPayrollManagement.setMaximumSize(new java.awt.Dimension(1467, 800));
                panelPayrollManagement.setMinimumSize(new java.awt.Dimension(1467, 800));
                panelPayrollManagement.setPreferredSize(new java.awt.Dimension(1467, 800));
                panelPayrollManagement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                pMenu.setBackground(new java.awt.Color(93, 0, 0));
                pMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/back.png"))); // NOI18N
                lbBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbBackButtonMouseClicked(evt);
                        }
                });
                pMenu.add(lbBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

                lbBuscar.setBackground(new java.awt.Color(0, 0, 0));
                lbBuscar.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                lbBuscar.setForeground(new java.awt.Color(245, 245, 245));
                lbBuscar.setText("Buscar:");
                lbBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                pMenu.add(lbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, 30));

                tfBuscar.setBackground(new java.awt.Color(231, 231, 231));
                tfBuscar.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfBuscar.setForeground(new java.awt.Color(20, 20, 20));
                tfBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                pMenu.add(tfBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 330, 30));

                panelPayrollManagement.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 60));

                lbEmpleados.setBackground(new java.awt.Color(0, 0, 0));
                lbEmpleados.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
                lbEmpleados.setForeground(new java.awt.Color(93, 0, 0));
                lbEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbEmpleados.setText("Empleados");
                lbEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                panelPayrollManagement.add(lbEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1470, 50));

                tTablaEmpleadosNomina.setBackground(new java.awt.Color(232, 232, 232));
                tTablaEmpleadosNomina.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tTablaEmpleadosNomina.setForeground(new java.awt.Color(20, 20, 20));
                tTablaEmpleadosNomina.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {"Juan Pérez", "juan@email.com", " Administrador", "Activo"},
                                {"María López ", "maria@email.com", "Empleado", "Inactivo"},
                                {"Carlos Ruiz", "carlos@email.com", "Cliente", "Activo"},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Nombre", "Correo", "Rol", "Estado"
                        }
                ));
                tTablaEmpleadosNomina.setShowGrid(false);
                spTablaEmpleadosNomina.setViewportView(tTablaEmpleadosNomina);

                panelPayrollManagement.add(spTablaEmpleadosNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 1050, 480));

                imgCalcularNomina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/calcularNomina.png"))); // NOI18N
                panelPayrollManagement.add(imgCalcularNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 670, -1, 60));

                btnCalcularNomina.setBackground(new java.awt.Color(93, 0, 0));
                btnCalcularNomina.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                btnCalcularNomina.setForeground(new java.awt.Color(200, 200, 200));
                btnCalcularNomina.setText("      Calcular Nómina");
                btnCalcularNomina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnCalcularNomina.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCalcularNominaActionPerformed(evt);
                        }
                });
                panelPayrollManagement.add(btnCalcularNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 670, 300, 60));

                imgHistorialPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/historial.png"))); // NOI18N
                panelPayrollManagement.add(imgHistorialPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 670, -1, 60));

                btnHistorialPagos.setBackground(new java.awt.Color(93, 0, 0));
                btnHistorialPagos.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                btnHistorialPagos.setForeground(new java.awt.Color(200, 200, 200));
                btnHistorialPagos.setText("      Ver Historial de Pagos");
                btnHistorialPagos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnHistorialPagos.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnHistorialPagosActionPerformed(evt);
                        }
                });
                panelPayrollManagement.add(btnHistorialPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 670, 330, 60));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelPayrollManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelPayrollManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnCalcularNominaActionPerformed(java.awt.event.ActionEvent evt) {
		
        }

        private void btnHistorialPagosActionPerformed(java.awt.event.ActionEvent evt) {
                
		HistoryPayroll hp = new HistoryPayroll();
                hp.setVisible(true);
                this.setVisible(false);
        }

        private void lbBackButtonMouseClicked(java.awt.event.MouseEvent evt) {
                
                DashboardAdminScreen dashboard = new DashboardAdminScreen();
                dashboard.setVisible(true);
                this.setVisible(false);
        }

	
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCalcularNomina;
        private javax.swing.JButton btnHistorialPagos;
        private javax.swing.JLabel imgCalcularNomina;
        private javax.swing.JLabel imgHistorialPagos;
        private javax.swing.JLabel lbBackButton;
        private javax.swing.JLabel lbBuscar;
        private javax.swing.JLabel lbEmpleados;
        private javax.swing.JPanel pMenu;
        private javax.swing.JPanel panelPayrollManagement;
        private javax.swing.JScrollPane spTablaEmpleadosNomina;
        private javax.swing.JTable tTablaEmpleadosNomina;
        private javax.swing.JTextField tfBuscar;
        // End of variables declaration//GEN-END:variables
}
