// cSpell: ignore descripcion categoria codigo
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.Gym360.view.admin.inventory;

import java.awt.Toolkit;

import javax.swing.JOptionPane;

import main.java.com.Gym360.controller.Verificar;
import main.java.com.Gym360.model.classes.Producto;
import main.java.com.Gym360.model.dao.ProductoDAO;
import main.java.com.Gym360.model.security.VerificarCampo;
import main.java.com.Gym360.util.ui.CambiarIU;
import main.java.com.Gym360.util.ui.ObtenerIU;

/**
 *
 * @author tutaa
 */
public class CreateProduct extends javax.swing.JFrame {

        /**
         * Creates new form ManageUsersScreen
         */
        public CreateProduct() {
                initComponents();
                this.setTitle("Registrar Producto");
                this.setResizable(false);
                this.setLocationRelativeTo(null);
                this.setIconImage(Toolkit.getDefaultToolkit()
                                .getImage(getClass().getResource("/main/resources/images/logo.png")));
                btnCrearProducto.setEnabled(datosValidos());
                mostrarErrores();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelCrearProducto = new javax.swing.JPanel();
                pMenu = new javax.swing.JPanel();
                lbBackButton = new javax.swing.JLabel();
                lbEditarProducto = new javax.swing.JLabel();
                lbNombre = new javax.swing.JLabel();
                tfNombre = new javax.swing.JTextField();
                imgValidarNombre = new javax.swing.JLabel();
                lbDescripcion = new javax.swing.JLabel();
                spDescripcion = new javax.swing.JScrollPane();
                taDescripcion = new javax.swing.JTextArea();
                imgValidarDescripcion = new javax.swing.JLabel();
                lbPrecioUnidad = new javax.swing.JLabel();
                tfPrecioUnidad = new javax.swing.JTextField();
                imgValidarPrecio = new javax.swing.JLabel();
                lbStock = new javax.swing.JLabel();
                tfStock = new javax.swing.JTextField();
                imgValidarStock = new javax.swing.JLabel();
                lbCategoria = new javax.swing.JLabel();
                cbCategoria = new javax.swing.JComboBox<>();
                imgValidarCategoria = new javax.swing.JLabel();
                imgCrearProducto = new javax.swing.JLabel();
                btnCrearProducto = new javax.swing.JButton();
                lbCodigoBarras = new javax.swing.JLabel();
                tfCodigoBarras = new javax.swing.JTextField();
                imgValidarCodigoBarras = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                panelCrearProducto.setBackground(new java.awt.Color(245, 245, 245));
                panelCrearProducto.setMaximumSize(new java.awt.Dimension(1467, 800));
                panelCrearProducto.setMinimumSize(new java.awt.Dimension(1467, 800));
                panelCrearProducto.setPreferredSize(new java.awt.Dimension(1467, 800));
                panelCrearProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                pMenu.setBackground(new java.awt.Color(93, 0, 0));
                pMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbBackButton.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/back.png"))); // NOI18N
                lbBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbBackButtonMouseClicked(evt);
                        }
                });
                pMenu.add(lbBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

                lbEditarProducto.setBackground(new java.awt.Color(0, 0, 0));
                lbEditarProducto.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
                lbEditarProducto.setForeground(new java.awt.Color(245, 245, 245));
                lbEditarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbEditarProducto.setText("CREAR PRODUCTO");
                lbEditarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                pMenu.add(lbEditarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

                panelCrearProducto.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

                lbNombre.setBackground(new java.awt.Color(0, 0, 0));
                lbNombre.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbNombre.setForeground(new java.awt.Color(20, 20, 20));
                lbNombre.setText("Nombre:");
                panelCrearProducto.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 40));

                tfNombre.setBackground(new java.awt.Color(231, 231, 231));
                tfNombre.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfNombre.setForeground(new java.awt.Color(20, 20, 20));
                tfNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfNombreKeyReleased(evt);
                        }
                });
                panelCrearProducto.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 280, 40));

                imgValidarNombre.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelCrearProducto.add(imgValidarNombre,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 30, 30));

                lbDescripcion.setBackground(new java.awt.Color(0, 0, 0));
                lbDescripcion.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbDescripcion.setForeground(new java.awt.Color(20, 20, 20));
                lbDescripcion.setText("Descripción:");
                panelCrearProducto.add(lbDescripcion,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 40));

                taDescripcion.setBackground(new java.awt.Color(231, 231, 231));
                taDescripcion.setColumns(20);
                taDescripcion.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                taDescripcion.setForeground(new java.awt.Color(20, 20, 20));
                taDescripcion.setLineWrap(true);
                taDescripcion.setRows(5);
                taDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                taDescripcionKeyReleased(evt);
                        }
                });
                spDescripcion.setViewportView(taDescripcion);

                panelCrearProducto.add(spDescripcion,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 280, -1));

                imgValidarDescripcion.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelCrearProducto.add(imgValidarDescripcion,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 30, 30));

                lbPrecioUnidad.setBackground(new java.awt.Color(0, 0, 0));
                lbPrecioUnidad.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbPrecioUnidad.setForeground(new java.awt.Color(20, 20, 20));
                lbPrecioUnidad.setText("Precio Unidad:");
                panelCrearProducto.add(lbPrecioUnidad,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, 40));

                tfPrecioUnidad.setBackground(new java.awt.Color(231, 231, 231));
                tfPrecioUnidad.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfPrecioUnidad.setForeground(new java.awt.Color(20, 20, 20));
                tfPrecioUnidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                tfPrecioUnidad.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfPrecioUnidadKeyReleased(evt);
                        }
                });
                panelCrearProducto.add(tfPrecioUnidad,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 280, 40));

                imgValidarPrecio.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelCrearProducto.add(imgValidarPrecio,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 30, 30));

                lbStock.setBackground(new java.awt.Color(0, 0, 0));
                lbStock.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbStock.setForeground(new java.awt.Color(20, 20, 20));
                lbStock.setText("Stock:");
                panelCrearProducto.add(lbStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, 40));

                tfStock.setBackground(new java.awt.Color(231, 231, 231));
                tfStock.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfStock.setForeground(new java.awt.Color(20, 20, 20));
                tfStock.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                tfStock.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfStockKeyReleased(evt);
                        }
                });
                panelCrearProducto.add(tfStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 90, 40));

                imgValidarStock.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelCrearProducto.add(imgValidarStock,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 30, 30));

                lbCategoria.setBackground(new java.awt.Color(0, 0, 0));
                lbCategoria.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbCategoria.setForeground(new java.awt.Color(20, 20, 20));
                lbCategoria.setText("Categoria:");
                panelCrearProducto.add(lbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, 40));

                cbCategoria.setBackground(new java.awt.Color(231, 231, 231));
                cbCategoria.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                cbCategoria.setForeground(new java.awt.Color(20, 20, 20));
                cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Seleccionar", "Suplementos", "Accesorios", "Ropa", "Equipos" }));
                cbCategoria.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbCategoriaActionPerformed(evt);
                        }
                });
                panelCrearProducto.add(cbCategoria,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 280, 40));

                imgValidarCategoria.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelCrearProducto.add(imgValidarCategoria,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 30, 30));

                imgCrearProducto.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/plus.png"))); // NOI18N
                panelCrearProducto.add(imgCrearProducto,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 670, 40, 60));

                btnCrearProducto.setBackground(new java.awt.Color(93, 0, 0));
                btnCrearProducto.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                btnCrearProducto.setForeground(new java.awt.Color(200, 200, 200));
                btnCrearProducto.setText("      Crear Producto");
                btnCrearProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnCrearProducto.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCrearProductoActionPerformed(evt);
                        }
                });
                panelCrearProducto.add(btnCrearProducto,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, 300, 60));

                lbCodigoBarras.setBackground(new java.awt.Color(0, 0, 0));
                lbCodigoBarras.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbCodigoBarras.setForeground(new java.awt.Color(20, 20, 20));
                lbCodigoBarras.setText("Codigo de Barras:");
                panelCrearProducto.add(lbCodigoBarras,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, -1, 40));

                tfCodigoBarras.setBackground(new java.awt.Color(231, 231, 231));
                tfCodigoBarras.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfCodigoBarras.setForeground(new java.awt.Color(20, 20, 20));
                tfCodigoBarras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                tfCodigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfCodigoBarrasKeyReleased(evt);
                        }
                });
                panelCrearProducto.add(tfCodigoBarras,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, 230, 40));

                imgValidarCodigoBarras.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/error.png"))); // NOI18N
                panelCrearProducto.add(imgValidarCodigoBarras,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 590, 30, 30));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelCrearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 675,
                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelCrearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 760,
                                                javax.swing.GroupLayout.PREFERRED_SIZE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void tfCodigoBarrasKeyReleased(java.awt.event.KeyEvent evt) {
                btnCrearProducto.setEnabled(datosValidos());
                mostrarErrores();
        }

        private void tfNombreKeyReleased(java.awt.event.KeyEvent evt) {
                btnCrearProducto.setEnabled(datosValidos());
                mostrarErrores();

        }

        private void taDescripcionKeyReleased(java.awt.event.KeyEvent evt) {
                btnCrearProducto.setEnabled(datosValidos());
                mostrarErrores();
        }

        private void tfPrecioUnidadKeyReleased(java.awt.event.KeyEvent evt) {
                btnCrearProducto.setEnabled(datosValidos());
                mostrarErrores();
        }

        private void tfStockKeyReleased(java.awt.event.KeyEvent evt) {
                btnCrearProducto.setEnabled(datosValidos());
                mostrarErrores();
        }

        private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProducto.setEnabled(datosValidos());
                mostrarErrores();
        }

        private void btnCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {
                crearProducto();

        }

        private void lbBackButtonMouseClicked(java.awt.event.MouseEvent evt) {

                ManageInventoryScreen mi = new ManageInventoryScreen();
                mi.setVisible(true);
                this.setVisible(false);
        }

        private boolean datosValidos() {
                return Verificar.validarNombre(ObtenerIU.obtenerTextoCampo(tfNombre))
                                && Verificar.validarDescripcion(ObtenerIU.obtenerTextoArea(taDescripcion))
                                && Verificar.validarPrecio((ObtenerIU.obtenerTextoCampo(tfPrecioUnidad)))
                                && Verificar.validarStock((ObtenerIU.obtenerTextoCampo(tfStock)))
                                && Verificar.validarComboBox(ObtenerIU.obtenerSeleccionCombo(cbCategoria))
                                && Verificar.validarYVerificarCodigoBarras(
                                                (ObtenerIU.obtenerTextoCampo(tfCodigoBarras)),
                                                ManageInventoryScreen.idProductoSeleccionado);

        }

        private void mostrarErrores() {

                // tfNombre
                VerificarCampo.verificarCampo(Verificar.validarNombre(ObtenerIU.obtenerTextoCampo(tfNombre)),
                                imgValidarNombre, "El nombre es válido.", "El nombre no es válido.");

                // taDescripcion
                VerificarCampo.verificarCampo(Verificar.validarDescripcion(ObtenerIU.obtenerTextoArea(taDescripcion)),
                                imgValidarDescripcion, "La descripcion no es válida.", "La descripcion es válida.");
                // tfPrecioUnitario
                VerificarCampo.verificarCampo(Verificar.validarPrecio((ObtenerIU.obtenerTextoCampo(tfPrecioUnidad))),
                                imgValidarPrecio, "El precio unitario es válido.", "El precio unitario no es válido.");
                // tfStock
                VerificarCampo.verificarCampo(Verificar.validarStock((ObtenerIU.obtenerTextoCampo(tfStock))),
                                imgValidarStock, "El stock es válido.", "El stock no es válido.");
                // tfCodigoBarras
                VerificarCampo.verificarCampo(
                                Verificar.validarYVerificarCodigoBarras((ObtenerIU.obtenerTextoCampo(tfCodigoBarras)),
                                                ManageInventoryScreen.idProductoSeleccionado),
                                imgValidarCodigoBarras, "El codigo de barras es válido.",
                                "El codigo de barras no es válido o ya está registrado.");
                // cbCategoria
                VerificarCampo.verificarCampo(Verificar.validarComboBox(ObtenerIU.obtenerSeleccionCombo(cbCategoria)),
                                imgValidarCategoria, "Ha seleccionado una categoría.",
                                "Debe seleccionar una categoría.");

        }

        private void crearProducto() {
                ProductoDAO productoDAO = new ProductoDAO();
                String nombre = ObtenerIU.obtenerTextoCampo(tfNombre);
                String descripcion = ObtenerIU.obtenerTextoArea(taDescripcion);
                Double precioUnidad = Double.parseDouble(ObtenerIU.obtenerTextoCampo(tfPrecioUnidad));
                int stock = Integer.parseInt(ObtenerIU.obtenerTextoCampo(tfStock));
                String categoria = ObtenerIU.obtenerSeleccionCombo(cbCategoria);
                String codigoBarras = (ObtenerIU.obtenerTextoCampo(tfCodigoBarras));

                try {
                        productoDAO.insertar(new Producto(0, nombre, descripcion, precioUnidad, stock, categoria,
                                        codigoBarras));
                        JOptionPane.showMessageDialog(this, "El producto se registró correctamente.",
                                        "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
                        ManageInventoryScreen mi = new ManageInventoryScreen();
                        mi.setVisible(true);
                        this.setVisible(false);

                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el producto.", "Error",
                                        JOptionPane.ERROR_MESSAGE);

                }

        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCrearProducto;
        private javax.swing.JComboBox<String> cbCategoria;
        private javax.swing.JLabel imgCrearProducto;
        private javax.swing.JLabel imgValidarCategoria;
        private javax.swing.JLabel imgValidarCodigoBarras;
        private javax.swing.JLabel imgValidarDescripcion;
        private javax.swing.JLabel imgValidarNombre;
        private javax.swing.JLabel imgValidarPrecio;
        private javax.swing.JLabel imgValidarStock;
        private javax.swing.JLabel lbBackButton;
        private javax.swing.JLabel lbCategoria;
        private javax.swing.JLabel lbCodigoBarras;
        private javax.swing.JLabel lbDescripcion;
        private javax.swing.JLabel lbEditarProducto;
        private javax.swing.JLabel lbNombre;
        private javax.swing.JLabel lbPrecioUnidad;
        private javax.swing.JLabel lbStock;
        private javax.swing.JPanel pMenu;
        private javax.swing.JPanel panelCrearProducto;
        private javax.swing.JScrollPane spDescripcion;
        private javax.swing.JTextArea taDescripcion;
        private javax.swing.JTextField tfCodigoBarras;
        private javax.swing.JTextField tfNombre;
        private javax.swing.JTextField tfPrecioUnidad;
        private javax.swing.JTextField tfStock;
        // End of variables declaration//GEN-END:variables
}
