/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.Gym360.view.admin.inventory;

import main.java.com.Gym360.view.admin.users.*;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.EventQueue;
import java.awt.Toolkit;
import javax.swing.UIManager;

/**
 *
 * @author tutaa
 */
public class EditCompra extends javax.swing.JFrame {

	/**
	 * Creates new form ManageUsersScreen
	 */
	public EditCompra() {
		initComponents();
		this.setTitle("Editar Compra");
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/main/resources/images/logo.png")));
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelEditarCompra = new javax.swing.JPanel();
                pMenu = new javax.swing.JPanel();
                lbBackButton = new javax.swing.JLabel();
                lbEditarCompra = new javax.swing.JLabel();
                lbFecha = new javax.swing.JLabel();
                tfFecha = new javax.swing.JTextField();
                lbTotal = new javax.swing.JLabel();
                tfTotal = new javax.swing.JTextField();
                lbProveedor = new javax.swing.JLabel();
                cbProveedor = new javax.swing.JComboBox<>();
                imgEditarCompra = new javax.swing.JLabel();
                btnEditarCompra = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                panelEditarCompra.setBackground(new java.awt.Color(245, 245, 245));
                panelEditarCompra.setMaximumSize(new java.awt.Dimension(1467, 800));
                panelEditarCompra.setMinimumSize(new java.awt.Dimension(1467, 800));
                panelEditarCompra.setPreferredSize(new java.awt.Dimension(1467, 800));
                panelEditarCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                pMenu.setBackground(new java.awt.Color(93, 0, 0));
                pMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/back.png"))); // NOI18N
                lbBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbBackButtonMouseClicked(evt);
                        }
                });
                pMenu.add(lbBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

                lbEditarCompra.setBackground(new java.awt.Color(0, 0, 0));
                lbEditarCompra.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
                lbEditarCompra.setForeground(new java.awt.Color(245, 245, 245));
                lbEditarCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbEditarCompra.setText("EDITAR COMPRA");
                lbEditarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                pMenu.add(lbEditarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

                panelEditarCompra.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

                lbFecha.setBackground(new java.awt.Color(0, 0, 0));
                lbFecha.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbFecha.setForeground(new java.awt.Color(20, 20, 20));
                lbFecha.setText("Fecha:");
                panelEditarCompra.add(lbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 40));

                tfFecha.setBackground(new java.awt.Color(231, 231, 231));
                tfFecha.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfFecha.setForeground(new java.awt.Color(20, 20, 20));
                tfFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                panelEditarCompra.add(tfFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 280, 40));

                lbTotal.setBackground(new java.awt.Color(0, 0, 0));
                lbTotal.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbTotal.setForeground(new java.awt.Color(20, 20, 20));
                lbTotal.setText("Total:");
                panelEditarCompra.add(lbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 40));

                tfTotal.setBackground(new java.awt.Color(231, 231, 231));
                tfTotal.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfTotal.setForeground(new java.awt.Color(20, 20, 20));
                tfTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                panelEditarCompra.add(tfTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 280, 40));

                lbProveedor.setBackground(new java.awt.Color(0, 0, 0));
                lbProveedor.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbProveedor.setForeground(new java.awt.Color(20, 20, 20));
                lbProveedor.setText("Proveedor:");
                panelEditarCompra.add(lbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, 40));

                cbProveedor.setBackground(new java.awt.Color(231, 231, 231));
                cbProveedor.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                cbProveedor.setForeground(new java.awt.Color(20, 20, 20));
                cbProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                panelEditarCompra.add(cbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 280, 40));

                imgEditarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/editar.png"))); // NOI18N
                panelEditarCompra.add(imgEditarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 40, 60));

                btnEditarCompra.setBackground(new java.awt.Color(93, 0, 0));
                btnEditarCompra.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                btnEditarCompra.setForeground(new java.awt.Color(200, 200, 200));
                btnEditarCompra.setText("      Editar Compra");
                btnEditarCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnEditarCompra.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEditarCompraActionPerformed(evt);
                        }
                });
                panelEditarCompra.add(btnEditarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 300, 60));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelEditarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelEditarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnEditarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCompraActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_btnEditarCompraActionPerformed

        private void lbBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackButtonMouseClicked
                // TODO add your handling code here:
		ManageInventoryScreen mi = new ManageInventoryScreen();
		mi.setVisible(true);
		this.setVisible(false);
        }//GEN-LAST:event_lbBackButtonMouseClicked



        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnEditarCompra;
        private javax.swing.JComboBox<String> cbProveedor;
        private javax.swing.JLabel imgEditarCompra;
        private javax.swing.JLabel lbBackButton;
        private javax.swing.JLabel lbEditarCompra;
        private javax.swing.JLabel lbFecha;
        private javax.swing.JLabel lbProveedor;
        private javax.swing.JLabel lbTotal;
        private javax.swing.JPanel pMenu;
        private javax.swing.JPanel panelEditarCompra;
        private javax.swing.JTextField tfFecha;
        private javax.swing.JTextField tfTotal;
        // End of variables declaration//GEN-END:variables
}
