//cSpell:ignore gestion
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.Gym360.view.admin.inventory;

import java.awt.Toolkit;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import main.java.com.Gym360.model.classes.Producto;
import main.java.com.Gym360.model.dao.DetalleCompraDAO;
import main.java.com.Gym360.model.dao.ProductoDAO;
import main.java.com.Gym360.util.ui.CambiarIU;
import main.java.com.Gym360.view.admin.DashboardAdminScreen;

/**
 *
 * @author tutaa
 */
public class ManageInventoryScreen extends javax.swing.JFrame {

    public static int idCompraSeleccionada = -1;

    public static int idProductoSeleccionado = -1;

    /**
     * Creates new form ManageInventoryScreen
     */
    public ManageInventoryScreen() {
        initComponents();
        this.setTitle("Gestión de Inventario");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(
                Toolkit.getDefaultToolkit().getImage(getClass().getResource("/main/resources/images/logo.png")));
        cargarTablaProductos("");
        cargarTablaCompras("");

        CambiarIU.deshabilitarBotones(btnEditarProducto, btnEliminarProducto);
        CambiarIU.deshabilitarBotones(btnEditarCompra, btnEliminarCompra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGestionInventario = new javax.swing.JPanel();
        pMenu = new javax.swing.JPanel();
        lbBackButton = new javax.swing.JLabel();
        lbBuscarCompras = new javax.swing.JLabel();
        tfBuscarCompras = new javax.swing.JTextField();
        lbBuscarProductos = new javax.swing.JLabel();
        tfBuscarProductos = new javax.swing.JTextField();
        lbCompras = new javax.swing.JLabel();
        spTablaCompras = new javax.swing.JScrollPane();
        tCompras = new javax.swing.JTable();
        btnRegistrarCompra = new javax.swing.JButton();
        btnEditarCompra = new javax.swing.JButton();
        btnEliminarCompra = new javax.swing.JButton();
        lbProductos = new javax.swing.JLabel();
        spTablaProductos = new javax.swing.JScrollPane();
        tProductos = new javax.swing.JTable();
        btnAgregarProducto = new javax.swing.JButton();
        btnEditarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGestionInventario.setBackground(new java.awt.Color(245, 245, 245));
        panelGestionInventario.setMaximumSize(new java.awt.Dimension(1467, 800));
        panelGestionInventario.setMinimumSize(new java.awt.Dimension(1467, 800));
        panelGestionInventario.setPreferredSize(new java.awt.Dimension(1467, 800));
        panelGestionInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pMenu.setBackground(new java.awt.Color(93, 0, 0));
        pMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/back.png"))); // NOI18N
        lbBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBackButtonMouseClicked(evt);
            }
        });
        pMenu.add(lbBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        lbBuscarCompras.setBackground(new java.awt.Color(0, 0, 0));
        lbBuscarCompras.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        lbBuscarCompras.setForeground(new java.awt.Color(245, 245, 245));
        lbBuscarCompras.setText("Buscar:");
        lbBuscarCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pMenu.add(lbBuscarCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, 30));

        tfBuscarCompras.setBackground(new java.awt.Color(231, 231, 231));
        tfBuscarCompras.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        tfBuscarCompras.setForeground(new java.awt.Color(20, 20, 20));
        tfBuscarCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfBuscarCompras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBuscarComprasKeyReleased(evt);
            }
        });
        pMenu.add(tfBuscarCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 330, 30));

        lbBuscarProductos.setBackground(new java.awt.Color(0, 0, 0));
        lbBuscarProductos.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        lbBuscarProductos.setForeground(new java.awt.Color(245, 245, 245));
        lbBuscarProductos.setText("Buscar:");
        lbBuscarProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pMenu.add(lbBuscarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, 30));

        tfBuscarProductos.setBackground(new java.awt.Color(231, 231, 231));
        tfBuscarProductos.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        tfBuscarProductos.setForeground(new java.awt.Color(20, 20, 20));
        tfBuscarProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfBuscarProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBuscarProductosKeyReleased(evt);
            }
        });
        pMenu.add(tfBuscarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 330, 30));

        panelGestionInventario.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 60));

        lbCompras.setBackground(new java.awt.Color(0, 0, 0));
        lbCompras.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lbCompras.setForeground(new java.awt.Color(93, 0, 0));
        lbCompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCompras.setText("Compras");
        lbCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelGestionInventario.add(lbCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 590, 70));

        tCompras.setBackground(new java.awt.Color(232, 232, 232));
        tCompras.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        tCompras.setForeground(new java.awt.Color(20, 20, 20));
        tCompras.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] { { "Juan Pérez", "juan@email.com", " Administrador", "Activo" },
                        { "María López ", "maria@email.com", "Empleado", "Inactivo" },
                        { "Carlos Ruiz", "carlos@email.com", "Cliente", "Activo" }, { null, null, null, null } },
                new String[] { "Nombre", "Correo", "Rol", "Estado" }));
        tCompras.setShowGrid(false);
        tCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tComprasMouseClicked(evt);
            }
        });
        spTablaCompras.setViewportView(tCompras);

        panelGestionInventario.add(spTablaCompras,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 590, 500));

        btnRegistrarCompra.setBackground(new java.awt.Color(93, 0, 0));
        btnRegistrarCompra.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnRegistrarCompra.setForeground(new java.awt.Color(200, 200, 200));
        btnRegistrarCompra.setText("Registrar Compra");
        btnRegistrarCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCompraActionPerformed(evt);
            }
        });
        panelGestionInventario.add(btnRegistrarCompra,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 650, -1, 50));

        btnEditarCompra.setBackground(new java.awt.Color(93, 0, 0));
        btnEditarCompra.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnEditarCompra.setForeground(new java.awt.Color(200, 200, 200));
        btnEditarCompra.setText("Editar Compra");
        btnEditarCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCompraActionPerformed(evt);
            }
        });
        panelGestionInventario.add(btnEditarCompra,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 650, -1, 50));

        btnEliminarCompra.setBackground(new java.awt.Color(93, 0, 0));
        btnEliminarCompra.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnEliminarCompra.setForeground(new java.awt.Color(200, 200, 200));
        btnEliminarCompra.setText("Eliminar Compra");
        btnEliminarCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEliminarCompra.setOpaque(true);
        btnEliminarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCompraActionPerformed(evt);
            }
        });
        panelGestionInventario.add(btnEliminarCompra,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 710, 190, 50));

        lbProductos.setBackground(new java.awt.Color(0, 0, 0));
        lbProductos.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lbProductos.setForeground(new java.awt.Color(93, 0, 0));
        lbProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbProductos.setText("Productos");
        lbProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelGestionInventario.add(lbProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 590, 70));

        tProductos.setBackground(new java.awt.Color(232, 232, 232));
        tProductos.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        tProductos.setForeground(new java.awt.Color(20, 20, 20));
        tProductos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] { { "Juan Pérez", "juan@email.com", " Administrador", "Activo" },
                        { "María López ", "maria@email.com", "Empleado", "Inactivo" },
                        { "Carlos Ruiz", "carlos@email.com", "Cliente", "Activo" }, { null, null, null, null } },
                new String[] { "Nombre", "Correo", "Rol", "Estado" }));
        tProductos.setShowGrid(false);
        tProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tProductosMouseClicked(evt);
            }
        });
        spTablaProductos.setViewportView(tProductos);

        panelGestionInventario.add(spTablaProductos,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 590, 500));

        btnAgregarProducto.setBackground(new java.awt.Color(93, 0, 0));
        btnAgregarProducto.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(200, 200, 200));
        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        panelGestionInventario.add(btnAgregarProducto,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 650, -1, 50));

        btnEditarProducto.setBackground(new java.awt.Color(93, 0, 0));
        btnEditarProducto.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnEditarProducto.setForeground(new java.awt.Color(200, 200, 200));
        btnEditarProducto.setText("Editar Producto");
        btnEditarProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProductoActionPerformed(evt);
            }
        });
        panelGestionInventario.add(btnEditarProducto,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 650, -1, 50));

        btnEliminarProducto.setBackground(new java.awt.Color(93, 0, 0));
        btnEliminarProducto.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnEliminarProducto.setForeground(new java.awt.Color(200, 200, 200));
        btnEliminarProducto.setText("Eliminar Producto");
        btnEliminarProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        panelGestionInventario.add(btnEliminarProducto,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 710, 200, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                panelGestionInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                panelGestionInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tComprasMouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = tCompras.getSelectedRow();
        idCompraSeleccionada = Integer.parseInt(tCompras.getValueAt(selectedRow, 1).toString());

        if (idCompraSeleccionada != -1) {
            CambiarIU.habilitarBotones(btnEditarCompra, btnEliminarCompra);
        }
    }

    private void tProductosMouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = tProductos.getSelectedRow();

        idProductoSeleccionado = Integer.parseInt(tProductos.getValueAt(selectedRow, 0).toString());
        if (idProductoSeleccionado != -1) {
            CambiarIU.habilitarBotones(btnEditarProducto, btnEliminarProducto);
        }

    }

    private void tfBuscarComprasKeyReleased(java.awt.event.KeyEvent evt) {
        filtrarTablaCompras();
    }

    private void tfBuscarProductosKeyReleased(java.awt.event.KeyEvent evt) {
        filtrarTablaProductos();
    }

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {
        CreateProduct cp = new CreateProduct();
        cp.setVisible(true);
        this.setVisible(false);

    }

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {
        ProductoDAO productoDAO = new ProductoDAO();
        productoDAO.eliminar(idProductoSeleccionado);
        idProductoSeleccionado = -1;
        cargarTablaProductos("");
        CambiarIU.deshabilitarBotones(btnEditarProducto, btnEliminarProducto);
        CambiarIU.deshabilitarBotones(btnEditarCompra, btnEliminarCompra);
    }

    private void btnEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {
        EditProduct ep = new EditProduct();
        ep.setVisible(true);
        this.setVisible(false);
    }

    private void btnEliminarCompraActionPerformed(java.awt.event.ActionEvent evt) {
        DetalleCompraDAO detalleCompraDAO = new DetalleCompraDAO();
        detalleCompraDAO.eliminar(idCompraSeleccionada);
        idCompraSeleccionada = -1;
        cargarTablaCompras("");
        CambiarIU.deshabilitarBotones(btnEditarProducto, btnEliminarProducto);
        CambiarIU.deshabilitarBotones(btnEditarCompra, btnEliminarCompra);

    }

    private void btnRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {
        CreateCompra cc = new CreateCompra();
        cc.setVisible(true);
        this.setVisible(false);
    }

    private void btnEditarCompraActionPerformed(java.awt.event.ActionEvent evt) {
        EditCompra ec = new EditCompra();
        ec.setVisible(true);
        this.setVisible(false);
    }

    private void lbBackButtonMouseClicked(java.awt.event.MouseEvent evt) {
        DashboardAdminScreen dashboard = new DashboardAdminScreen();
        dashboard.setVisible(true);
        this.setVisible(false);
    }
    // Método que filtra la tabla

    private void filtrarTablaCompras() {
        String filtro = tfBuscarCompras.getText().trim();
        cargarTablaCompras(filtro); // Llamamos al método con el filtro actual
    }

    private void filtrarTablaProductos() {
        String filtro = tfBuscarProductos.getText().trim();
        cargarTablaProductos(filtro); // Llamamos al método con el filtro actual
    }

    public void cargarTablaCompras(String filtro) {
        // Obtenemos los detalles de compra usando el DAO y el filtro
        DetalleCompraDAO detalleCompraDAO = new DetalleCompraDAO();
        List<Object[]> detallesCompra = detalleCompraDAO.obtenerDetallesDeComprasConFiltro(filtro);

        // Crear un modelo de tabla con las columnas adecuadas
        String[] columnas = { "ID Detalle Compra", "ID Compra", "Producto", "Descripción", "Cantidad",
                "Precio Unitario", "Total Producto" };
        DefaultTableModel model = new DefaultTableModel(columnas, 0);

        // Llenamos la tabla con los datos
        for (Object[] detalle : detallesCompra) {
            model.addRow(detalle);
        }

        // Asignamos el modelo a la tabla
        tCompras.setModel(model);
    }

    public void cargarTablaProductos(String filtro) {
        // Crear instancia del DAO para obtener los productos filtrados
        ProductoDAO productoDAO = new ProductoDAO();
        List<Producto> listaProductos = productoDAO.obtenerProductosConFiltro(filtro);

        // Crear el modelo para el JTable
        String[] columnNames = { "ID Producto", "Nombre", "Descripción", "Precio Unitario", "Stock", "Categoría",
                "Código de Barras" };
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        // Agregar los productos al modelo
        for (Producto producto : listaProductos) {
            Object[] row = { producto.getIdProducto(), producto.getNombre(), producto.getDescripcion(),
                    producto.getPrecioUnitario(), producto.getStock(), producto.getCategoria(),
                    producto.getCodigoBarras() };
            model.addRow(row);
        }

        // Asignar el modelo al JTable (tProductos)
        tProductos.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnEditarCompra;
    private javax.swing.JButton btnEditarProducto;
    private javax.swing.JButton btnEliminarCompra;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnRegistrarCompra;
    private javax.swing.JLabel lbBackButton;
    private javax.swing.JLabel lbBuscarCompras;
    private javax.swing.JLabel lbBuscarProductos;
    private javax.swing.JLabel lbCompras;
    private javax.swing.JLabel lbProductos;
    private javax.swing.JPanel pMenu;
    private javax.swing.JPanel panelGestionInventario;
    private javax.swing.JScrollPane spTablaCompras;
    private javax.swing.JScrollPane spTablaProductos;
    private javax.swing.JTable tCompras;
    private javax.swing.JTable tProductos;
    private javax.swing.JTextField tfBuscarCompras;
    private javax.swing.JTextField tfBuscarProductos;
    // End of variables declaration//GEN-END:variables
}
