// cSpell:ignore recuerdame recuérdame boton desencriptar
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.Gym360.view;

import java.awt.EventQueue;
import java.awt.Toolkit;

import main.java.com.Gym360.controller.Ingresar;
import main.java.com.Gym360.util.ui.CambiarIU;
import main.java.com.Gym360.view.admin.DashboardAdminScreen;
import main.java.com.Gym360.view.customer.DashboardClientScreen;
import main.java.com.Gym360.view.employee.DashboardEmployeeScreen;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import main.java.com.Gym360.controller.Verificar;
import main.java.com.Gym360.model.security.DatosUsuario;
import main.java.com.Gym360.model.security.Desencriptar;
import main.java.com.Gym360.util.ui.ObtenerIU;

/**
 *
 * @author tutaa
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setTitle("Ingresar");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(
                Toolkit.getDefaultToolkit().getImage(getClass().getResource("/main/resources/images/logo.png")));
        tfCorreo.requestFocus();
        new CambiarIU().setImageLabel(lbImagenFondo, "/main/resources/images/fondoLogin.jpg");
        new CambiarIU().setImageLabel(lbImagenLogo, "/main/resources/images/logo.png");

        cargarDatos();

        desactivarBotonIngresar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogin = new javax.swing.JPanel();
        lbImagenLogo = new javax.swing.JLabel();
        lbImagenFondo = new javax.swing.JLabel();
        lbCorreo = new javax.swing.JLabel();
        tfCorreo = new javax.swing.JTextField();
        lbContraseña = new javax.swing.JLabel();
        pfContraseña = new javax.swing.JPasswordField();
        cbRecuerdame = new javax.swing.JCheckBox();
        btnIngresar = new javax.swing.JButton();
        lbOlvidasteContraseña = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelLogin.setBackground(new java.awt.Color(245, 245, 245));
        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbImagenLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PanelLogin.add(lbImagenLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 290, 290));

        lbImagenFondo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelLogin.add(lbImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 0, 1050, 800));

        lbCorreo.setBackground(new java.awt.Color(0, 0, 0));
        lbCorreo.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        lbCorreo.setForeground(new java.awt.Color(20, 20, 20));
        lbCorreo.setText("Correo electrónico:");
        PanelLogin.add(lbCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        tfCorreo.setBackground(new java.awt.Color(231, 231, 231));
        tfCorreo.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        tfCorreo.setForeground(new java.awt.Color(20, 20, 20));
        tfCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCorreoKeyReleased(evt);
            }
        });
        PanelLogin.add(tfCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 330, 50));

        lbContraseña.setBackground(new java.awt.Color(0, 0, 0));
        lbContraseña.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        lbContraseña.setForeground(new java.awt.Color(20, 20, 20));
        lbContraseña.setText("Contraseña:");
        PanelLogin.add(lbContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        pfContraseña.setBackground(new java.awt.Color(231, 231, 231));
        pfContraseña.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        pfContraseña.setForeground(new java.awt.Color(20, 20, 20));
        pfContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pfContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pfContraseñaKeyReleased(evt);
            }
        });
        PanelLogin.add(pfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 330, 50));

        cbRecuerdame.setBackground(new java.awt.Color(245, 245, 245));
        cbRecuerdame.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        cbRecuerdame.setForeground(new java.awt.Color(20, 20, 20));
        cbRecuerdame.setSelected(true);
        cbRecuerdame.setText("Recuérdame");
        PanelLogin.add(cbRecuerdame, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        btnIngresar.setBackground(new java.awt.Color(93, 0, 0));
        btnIngresar.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(200, 200, 200));
        btnIngresar.setText("Ingresar");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        PanelLogin.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 330, 50));

        lbOlvidasteContraseña.setBackground(new java.awt.Color(0, 0, 0));
        lbOlvidasteContraseña.setFont(new java.awt.Font("Inter", 2, 14)); // NOI18N
        lbOlvidasteContraseña.setForeground(new java.awt.Color(93, 0, 0));
        lbOlvidasteContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOlvidasteContraseña.setText("¿Olvidaste tú contraseña?");
        lbOlvidasteContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbOlvidasteContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbOlvidasteContraseñaMouseClicked(evt);
            }
        });
        PanelLogin.add(lbOlvidasteContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 760, 330, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(PanelLogin,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(PanelLogin,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pfContraseñaKeyReleased(java.awt.event.KeyEvent evt) {
        desactivarBotonIngresar();
    }

    private void tfCorreoKeyReleased(java.awt.event.KeyEvent evt) {
        desactivarBotonIngresar();
    }

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {
        String correo = ObtenerIU.obtenerTextoCampo(tfCorreo);
        char[] contraseña = ObtenerIU.obtenerContraseña(pfContraseña);

        if (Ingresar.UsuarioValido(correo, contraseña)) {

            if (Ingresar.obtenerCargo(correo, contraseña).equals("cliente")) {
                DashboardClientScreen dashboardC = new DashboardClientScreen();
                dashboardC.setVisible(true);
                this.setVisible(false);
            } else if (Ingresar.obtenerCargo(correo, contraseña).equals("empleado")) {
                DashboardEmployeeScreen dashboardE = new DashboardEmployeeScreen();
                dashboardE.setVisible(true);
                this.setVisible(false);
            } else if (Ingresar.obtenerCargo(correo, contraseña).equals("admin")) {
                DashboardAdminScreen dashboardA = new DashboardAdminScreen();
                dashboardA.setVisible(true);
                this.setVisible(false);
            }

            guardarDatos();

        } else {

            JOptionPane.showMessageDialog(this, "CORREO O CONTRASEÑA NO VALIDOS \n", "AVISO!",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

    }

    private void lbOlvidasteContraseñaMouseClicked(java.awt.event.MouseEvent evt) {

    }

    private void desactivarBotonIngresar() {
        if (Verificar.validarCorreo(ObtenerIU.obtenerTextoCampo(tfCorreo))
                && Verificar.validarContraseña(ObtenerIU.obtenerContraseña(pfContraseña))) {
            CambiarIU.habilitarBotones(btnIngresar);

        } else {

            CambiarIU.deshabilitarBotones(btnIngresar);
        }

    }

    private void guardarDatos() {
        if (cbRecuerdame.isSelected()) {

            new DatosUsuario().guardarInfo(ObtenerIU.obtenerTextoCampo(tfCorreo),
                    Desencriptar.desencriptarContra(ObtenerIU.obtenerContraseña(pfContraseña)));
        }
    }

    private void cargarDatos() {
        if (cbRecuerdame.isSelected()) {
            String[] datos = new DatosUsuario().obtenerInfo();
            CambiarIU.ponerTextoCampo(tfCorreo, datos[0]);
            CambiarIU.ponerTextoCampoContraseña(pfContraseña, datos[1]);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
        } catch (Exception e) {
            System.err.println("No se pudo aplicar FlatMacDarkLaf: " + e.getMessage());
        }
        EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JCheckBox cbRecuerdame;
    private javax.swing.JLabel lbContraseña;
    private javax.swing.JLabel lbCorreo;
    private javax.swing.JLabel lbImagenFondo;
    private javax.swing.JLabel lbImagenLogo;
    private javax.swing.JLabel lbOlvidasteContraseña;
    private javax.swing.JPasswordField pfContraseña;
    private javax.swing.JTextField tfCorreo;
    // End of variables declaration//GEN-END:variables
}
