// cSpell:ignore grafica egresos distribucion membresias gestion rapidas
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.Gym360.view.admin;

import java.awt.Toolkit;
import java.util.List;
import java.util.Random;

import main.java.com.Gym360.model.classes.Cliente;
import main.java.com.Gym360.model.classes.Contabilidad;
import main.java.com.Gym360.model.dao.ClienteDAO;
import main.java.com.Gym360.model.dao.ContabilidadDAO;
import main.java.com.Gym360.util.dates.Dates;
import main.java.com.Gym360.util.ui.CambiarIU;
import main.java.com.Gym360.view.Login;
import main.java.com.Gym360.view.admin.inventory.ManageInventoryScreen;
import main.java.com.Gym360.view.admin.payroll.PayrollManagementScreen;
import main.java.com.Gym360.view.admin.users.CreateUser;
import main.java.com.Gym360.view.admin.users.ManageUsersScreen;

/**
 *
 * @author tutaa
 */
public class DashboardAdminScreen extends javax.swing.JFrame {

        /**
         * Creates new form DashboardAdminScreen
         */
        public DashboardAdminScreen() {
                initComponents();
                this.setTitle("Dashboard Admin");
                this.setResizable(false);
                this.setLocationRelativeTo(null);
                this.setIconImage(Toolkit.getDefaultToolkit()
                                .getImage(getClass().getResource("/main/resources/images/logo.png")));
                new FinancialReportScreen().graficaIngresosVsEgresos(imgGrafica1);
                new FinancialReportScreen().graficaDistribucionMembresias(imgGrafica2);
                ponerIngresos();
                ponerMembresias();
                ponerClientesActivos();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelDashboard = new javax.swing.JPanel();
                pMenu = new javax.swing.JPanel();
                lbBackButton = new javax.swing.JLabel();
                lbDashboard = new javax.swing.JLabel();
                lbGestionUsuarios = new javax.swing.JLabel();
                lbInventario = new javax.swing.JLabel();
                lbReportes = new javax.swing.JLabel();
                lbNomina = new javax.swing.JLabel();
                lbNotificaciones = new javax.swing.JLabel();
                lbDashboardAdmin = new javax.swing.JLabel();
                pMembresiasActivas = new javax.swing.JPanel();
                lbMembresiasActivas = new javax.swing.JLabel();
                lbPonerMembresiasActivas = new javax.swing.JLabel();
                lbClientes = new javax.swing.JLabel();
                lbActivos = new javax.swing.JLabel();
                pIngresosMes = new javax.swing.JPanel();
                lbIngresosMes = new javax.swing.JLabel();
                lbPonerIngresosMes = new javax.swing.JLabel();
                lbMes = new javax.swing.JLabel();
                pClientesActivos = new javax.swing.JPanel();
                lbClientesActivos = new javax.swing.JLabel();
                lbHoy = new javax.swing.JLabel();
                lbPonerPorcentajeClientesActivos = new javax.swing.JLabel();
                lbPonerContadorClientesActivos = new javax.swing.JLabel();
                pInventarioFaltante = new javax.swing.JPanel();
                lbInventarioFaltante = new javax.swing.JLabel();
                lbPonerProducto1 = new javax.swing.JLabel();
                lbPonerProducto2 = new javax.swing.JLabel();
                lbPonerProducto3 = new javax.swing.JLabel();
                pGrafica1 = new javax.swing.JPanel();
                imgGrafica1 = new javax.swing.JLabel();
                pGrafica2 = new javax.swing.JPanel();
                imgGrafica2 = new javax.swing.JLabel();
                lbAccionesRapidas = new javax.swing.JLabel();
                imgGenerarReporte = new javax.swing.JLabel();
                imgAgregarUsuario = new javax.swing.JLabel();
                btnAgregarUsuario = new javax.swing.JButton();
                btnGenerarReporte = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(1467, 800));

                panelDashboard.setBackground(new java.awt.Color(245, 245, 245));
                panelDashboard.setMaximumSize(new java.awt.Dimension(1467, 800));
                panelDashboard.setMinimumSize(new java.awt.Dimension(1467, 800));
                panelDashboard.setPreferredSize(new java.awt.Dimension(1467, 800));
                panelDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                pMenu.setBackground(new java.awt.Color(93, 0, 0));
                pMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbBackButton.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/back.png"))); // NOI18N
                lbBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbBackButtonMouseClicked(evt);
                        }
                });
                pMenu.add(lbBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

                lbDashboard.setBackground(new java.awt.Color(0, 0, 0));
                lbDashboard.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                lbDashboard.setForeground(new java.awt.Color(245, 245, 245));
                lbDashboard.setText("Dashboard");
                lbDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbDashboardMouseClicked(evt);
                        }
                });
                pMenu.add(lbDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

                lbGestionUsuarios.setBackground(new java.awt.Color(0, 0, 0));
                lbGestionUsuarios.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                lbGestionUsuarios.setForeground(new java.awt.Color(245, 245, 245));
                lbGestionUsuarios.setText("Gestión de Usuarios");
                lbGestionUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbGestionUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbGestionUsuariosMouseClicked(evt);
                        }
                });
                pMenu.add(lbGestionUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

                lbInventario.setBackground(new java.awt.Color(0, 0, 0));
                lbInventario.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                lbInventario.setForeground(new java.awt.Color(245, 245, 245));
                lbInventario.setText("Inventario");
                lbInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbInventario.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbInventarioMouseClicked(evt);
                        }
                });
                pMenu.add(lbInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

                lbReportes.setBackground(new java.awt.Color(0, 0, 0));
                lbReportes.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                lbReportes.setForeground(new java.awt.Color(245, 245, 245));
                lbReportes.setText("Reportes");
                lbReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbReportes.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbReportesMouseClicked(evt);
                        }
                });
                pMenu.add(lbReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, -1, -1));

                lbNomina.setBackground(new java.awt.Color(0, 0, 0));
                lbNomina.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                lbNomina.setForeground(new java.awt.Color(245, 245, 245));
                lbNomina.setText("Empleados");
                lbNomina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbNomina.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbNominaMouseClicked(evt);
                        }
                });
                pMenu.add(lbNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, -1, -1));

                lbNotificaciones.setBackground(new java.awt.Color(0, 0, 0));
                lbNotificaciones.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                lbNotificaciones.setForeground(new java.awt.Color(245, 245, 245));
                lbNotificaciones.setText("Notificaciones");
                lbNotificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbNotificaciones.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbNotificacionesMouseClicked(evt);
                        }
                });
                pMenu.add(lbNotificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, -1, -1));

                panelDashboard.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 60));

                lbDashboardAdmin.setBackground(new java.awt.Color(0, 0, 0));
                lbDashboardAdmin.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
                lbDashboardAdmin.setForeground(new java.awt.Color(93, 0, 0));
                lbDashboardAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbDashboardAdmin.setText("Dashboard Administrador");
                lbDashboardAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                panelDashboard.add(lbDashboardAdmin,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 1230, 50));

                pMembresiasActivas.setBackground(new java.awt.Color(245, 245, 245));
                pMembresiasActivas.setBorder(
                                new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
                pMembresiasActivas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbMembresiasActivas.setBackground(new java.awt.Color(0, 0, 0));
                lbMembresiasActivas.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
                lbMembresiasActivas.setForeground(new java.awt.Color(20, 20, 20));
                lbMembresiasActivas.setText("Membresías Activas");
                pMembresiasActivas.add(lbMembresiasActivas,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

                lbPonerMembresiasActivas.setBackground(new java.awt.Color(0, 0, 0));
                lbPonerMembresiasActivas.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
                lbPonerMembresiasActivas.setForeground(new java.awt.Color(20, 20, 20));
                lbPonerMembresiasActivas.setText("325");
                pMembresiasActivas.add(lbPonerMembresiasActivas,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

                lbClientes.setBackground(new java.awt.Color(0, 0, 0));
                lbClientes.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
                lbClientes.setForeground(new java.awt.Color(20, 20, 20));
                lbClientes.setText("clientes");
                pMembresiasActivas.add(lbClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

                lbActivos.setBackground(new java.awt.Color(0, 0, 0));
                lbActivos.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
                lbActivos.setForeground(new java.awt.Color(0, 204, 0));
                lbActivos.setText("activos");
                pMembresiasActivas.add(lbActivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

                panelDashboard.add(pMembresiasActivas,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 250, 110));

                pIngresosMes.setBackground(new java.awt.Color(245, 245, 245));
                pIngresosMes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
                pIngresosMes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbIngresosMes.setBackground(new java.awt.Color(0, 0, 0));
                lbIngresosMes.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
                lbIngresosMes.setForeground(new java.awt.Color(20, 20, 20));
                lbIngresosMes.setText("Ingresos del mes");
                pIngresosMes.add(lbIngresosMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

                lbPonerIngresosMes.setBackground(new java.awt.Color(0, 0, 0));
                lbPonerIngresosMes.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
                lbPonerIngresosMes.setForeground(new java.awt.Color(20, 20, 20));
                lbPonerIngresosMes.setText("$8,000");
                pIngresosMes.add(lbPonerIngresosMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

                lbMes.setBackground(new java.awt.Color(0, 0, 0));
                lbMes.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
                lbMes.setForeground(new java.awt.Color(20, 20, 20));
                lbMes.setText("En el mes de Marzo");
                pIngresosMes.add(lbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

                panelDashboard.add(pIngresosMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 250, 110));

                pClientesActivos.setBackground(new java.awt.Color(245, 245, 245));
                pClientesActivos.setBorder(
                                new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
                pClientesActivos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbClientesActivos.setBackground(new java.awt.Color(0, 0, 0));
                lbClientesActivos.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
                lbClientesActivos.setForeground(new java.awt.Color(20, 20, 20));
                lbClientesActivos.setText("Clientes activos");
                pClientesActivos.add(lbClientesActivos,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

                lbHoy.setBackground(new java.awt.Color(0, 0, 0));
                lbHoy.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
                lbHoy.setForeground(new java.awt.Color(169, 0, 0));
                lbHoy.setText("hoy");
                pClientesActivos.add(lbHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

                lbPonerPorcentajeClientesActivos.setBackground(new java.awt.Color(0, 0, 0));
                lbPonerPorcentajeClientesActivos.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
                lbPonerPorcentajeClientesActivos.setForeground(new java.awt.Color(20, 20, 20));
                lbPonerPorcentajeClientesActivos.setText("30%");
                pClientesActivos.add(lbPonerPorcentajeClientesActivos,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

                lbPonerContadorClientesActivos.setBackground(new java.awt.Color(0, 0, 0));
                lbPonerContadorClientesActivos.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
                lbPonerContadorClientesActivos.setForeground(new java.awt.Color(20, 20, 20));
                lbPonerContadorClientesActivos.setText("98 clientes");
                pClientesActivos.add(lbPonerContadorClientesActivos,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

                panelDashboard.add(pClientesActivos,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 250, 110));

                pInventarioFaltante.setBackground(new java.awt.Color(245, 245, 245));
                pInventarioFaltante.setBorder(
                                new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
                pInventarioFaltante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbInventarioFaltante.setBackground(new java.awt.Color(0, 0, 0));
                lbInventarioFaltante.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
                lbInventarioFaltante.setForeground(new java.awt.Color(20, 20, 20));
                lbInventarioFaltante.setText("Inventario faltante");
                pInventarioFaltante.add(lbInventarioFaltante,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

                lbPonerProducto1.setBackground(new java.awt.Color(0, 0, 0));
                lbPonerProducto1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
                lbPonerProducto1.setForeground(new java.awt.Color(20, 20, 20));
                lbPonerProducto1.setText("Cinturón de levantamiento: -4 unidades");
                pInventarioFaltante.add(lbPonerProducto1,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 250, -1));

                lbPonerProducto2.setBackground(new java.awt.Color(0, 0, 0));
                lbPonerProducto2.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
                lbPonerProducto2.setForeground(new java.awt.Color(20, 20, 20));
                lbPonerProducto2.setText("Magnesio en polvo: -1 unidades");
                pInventarioFaltante.add(lbPonerProducto2,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 250, -1));

                lbPonerProducto3.setBackground(new java.awt.Color(0, 0, 0));
                lbPonerProducto3.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
                lbPonerProducto3.setForeground(new java.awt.Color(20, 20, 20));
                lbPonerProducto3.setText("Guantes de entrenamiento: -5 unidades");
                pInventarioFaltante.add(lbPonerProducto3,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, -1));

                panelDashboard.add(pInventarioFaltante,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 250, 110));

                pGrafica1.setBackground(new java.awt.Color(245, 245, 245));
                pGrafica1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
                pGrafica1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                pGrafica1.add(imgGrafica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 270));

                panelDashboard.add(pGrafica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 540, 270));

                pGrafica2.setBackground(new java.awt.Color(245, 245, 245));
                pGrafica2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
                pGrafica2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                pGrafica2.add(imgGrafica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 340));

                panelDashboard.add(pGrafica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 440, 430, 340));

                lbAccionesRapidas.setBackground(new java.awt.Color(0, 0, 0));
                lbAccionesRapidas.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                lbAccionesRapidas.setForeground(new java.awt.Color(20, 20, 20));
                lbAccionesRapidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbAccionesRapidas.setText("Acciones Rápidas");
                panelDashboard.add(lbAccionesRapidas,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 540, -1));

                imgGenerarReporte.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/main/resources/images/generarReporte.png"))); // NOI18N
                panelDashboard.add(imgGenerarReporte,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 600, -1, 80));

                imgAgregarUsuario.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/main/resources/images/agregarUsuario.png"))); // NOI18N
                panelDashboard.add(imgAgregarUsuario,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, -1, 80));

                btnAgregarUsuario.setBackground(new java.awt.Color(93, 0, 0));
                btnAgregarUsuario.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                btnAgregarUsuario.setForeground(new java.awt.Color(200, 200, 200));
                btnAgregarUsuario.setText("      Agregar Usuario");
                btnAgregarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAgregarUsuarioActionPerformed(evt);
                        }
                });
                panelDashboard.add(btnAgregarUsuario,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 540, 80));

                btnGenerarReporte.setBackground(new java.awt.Color(93, 0, 0));
                btnGenerarReporte.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                btnGenerarReporte.setForeground(new java.awt.Color(200, 200, 200));
                btnGenerarReporte.setText("      Generar Reporte");
                btnGenerarReporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnGenerarReporteActionPerformed(evt);
                        }
                });
                panelDashboard.add(btnGenerarReporte,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 540, 80));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {
                FinancialReportScreen fr = new FinancialReportScreen();
                fr.setVisible(true);
                this.setVisible(false);
        }

        private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
                CreateUser cu = new CreateUser();
                cu.setVisible(true);
                this.setVisible(false);
        }

        private void lbBackButtonMouseClicked(java.awt.event.MouseEvent evt) {

                Login login = new Login();
                login.setVisible(true);
                this.setVisible(false);
        }

        private void lbDashboardMouseClicked(java.awt.event.MouseEvent evt) {

        }

        private void lbGestionUsuariosMouseClicked(java.awt.event.MouseEvent evt) {
                ManageUsersScreen mus = new ManageUsersScreen();
                mus.setVisible(true);
                this.setVisible(false);
        }

        private void lbInventarioMouseClicked(java.awt.event.MouseEvent evt) {
                ManageInventoryScreen mi = new ManageInventoryScreen();
                mi.setVisible(true);
                this.setVisible(false);
        }

        private void lbReportesMouseClicked(java.awt.event.MouseEvent evt) {
                FinancialReportScreen fr = new FinancialReportScreen();
                fr.setVisible(true);
                this.setVisible(false);
        }

        private void lbNominaMouseClicked(java.awt.event.MouseEvent evt) {
                PayrollManagementScreen pm = new PayrollManagementScreen();
                pm.setVisible(true);
                this.setVisible(false);
        }

        private void lbNotificacionesMouseClicked(java.awt.event.MouseEvent evt) {
                NotificationsScreen ns = new NotificationsScreen();
                ns.setVisible(true);
                this.setVisible(false);
        }

        private void ponerIngresos() {
                String[] meses = { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto",
                                "Septiembre", "Octubre", "Noviembre", "Diciembre" };

                ContabilidadDAO dao = new ContabilidadDAO();
                List<Contabilidad> registros = dao.obtenerTodos();

                double totalIngresos = 0;

                for (Contabilidad c : registros) {
                        totalIngresos += c.getIngresos();
                }
                // Mostrar Ingresos y Egresos
                CambiarIU.ponerTextoEtiqueta(lbPonerIngresosMes, "$" + String.valueOf(totalIngresos));
                CambiarIU.ponerTextoEtiqueta(lbMes, "En el mes de " + meses[Integer.parseInt(Dates.obtenerMes()) - 1]);

        }

        private void ponerMembresias() {
                ClienteDAO dao = new ClienteDAO();
                List<Cliente> clientes = dao.obtenerTodos();
                CambiarIU.ponerTextoEtiqueta(lbPonerMembresiasActivas, String.valueOf(clientes.size()));
        }

        private void ponerClientesActivos() {
                Random rand = new Random();
                ClienteDAO dao = new ClienteDAO();
                List<Cliente> clientes = dao.obtenerTodos();
                int clientesTotales = clientes.size();
                int clientesActuales = rand.nextInt(0, clientesTotales / 2);

                int porcentajeClientesActivos = (clientesActuales * 100) / clientesTotales;

                CambiarIU.ponerTextoEtiqueta(lbPonerContadorClientesActivos,
                                String.valueOf(clientesActuales) + " clientes");
                CambiarIU.ponerTextoEtiqueta(lbPonerPorcentajeClientesActivos,
                                String.valueOf(porcentajeClientesActivos) + "%");

        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAgregarUsuario;
        private javax.swing.JButton btnGenerarReporte;
        private javax.swing.JLabel imgAgregarUsuario;
        private javax.swing.JLabel imgGenerarReporte;
        private javax.swing.JLabel imgGrafica1;
        private javax.swing.JLabel imgGrafica2;
        private javax.swing.JLabel lbAccionesRapidas;
        private javax.swing.JLabel lbActivos;
        private javax.swing.JLabel lbBackButton;
        private javax.swing.JLabel lbClientes;
        private javax.swing.JLabel lbClientesActivos;
        private javax.swing.JLabel lbDashboard;
        private javax.swing.JLabel lbDashboardAdmin;
        private javax.swing.JLabel lbGestionUsuarios;
        private javax.swing.JLabel lbHoy;
        private javax.swing.JLabel lbIngresosMes;
        private javax.swing.JLabel lbInventario;
        private javax.swing.JLabel lbInventarioFaltante;
        private javax.swing.JLabel lbMembresiasActivas;
        private javax.swing.JLabel lbMes;
        private javax.swing.JLabel lbNomina;
        private javax.swing.JLabel lbNotificaciones;
        private javax.swing.JLabel lbPonerContadorClientesActivos;
        private javax.swing.JLabel lbPonerIngresosMes;
        private javax.swing.JLabel lbPonerMembresiasActivas;
        private javax.swing.JLabel lbPonerPorcentajeClientesActivos;
        private javax.swing.JLabel lbPonerProducto1;
        private javax.swing.JLabel lbPonerProducto2;
        private javax.swing.JLabel lbPonerProducto3;
        private javax.swing.JLabel lbReportes;
        private javax.swing.JPanel pClientesActivos;
        private javax.swing.JPanel pGrafica1;
        private javax.swing.JPanel pGrafica2;
        private javax.swing.JPanel pIngresosMes;
        private javax.swing.JPanel pInventarioFaltante;
        private javax.swing.JPanel pMembresiasActivas;
        private javax.swing.JPanel pMenu;
        private javax.swing.JPanel panelDashboard;
        // End of variables declaration//GEN-END:variables
}
