// cSpell:ignore grafica distribucion membresias egresos
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.Gym360.view.admin;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

import main.java.com.Gym360.model.classes.Cliente;
import main.java.com.Gym360.model.classes.Contabilidad;
import main.java.com.Gym360.model.dao.ClienteDAO;
import main.java.com.Gym360.model.dao.ContabilidadDAO;
import main.java.com.Gym360.util.ui.CambiarIU;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.RingPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;

/**
 *
 * @author tutaa
 */
//TODO: hacer un balance o cualquier calculo financiero
public class FinancialReportScreen extends javax.swing.JFrame {

        /**
         * Creates new form FinancialReportScreen
         */
        public FinancialReportScreen() {
                initComponents();
                this.setTitle("Reportes Financieros");
                this.setResizable(false);
                this.setLocationRelativeTo(null);
                this.setIconImage(Toolkit.getDefaultToolkit()
                                .getImage(getClass().getResource("/main/resources/images/logo.png")));
                graficaIngresosVsEgresos(imgGrafica1);
                graficaDistribucionMembresias(imgGrafica2);
                ponerInformacion();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelFinancialReport = new javax.swing.JPanel();
                pMenu = new javax.swing.JPanel();
                lbBackButton = new javax.swing.JLabel();
                pGrafica1 = new javax.swing.JPanel();
                imgGrafica1 = new javax.swing.JLabel();
                pGrafica2 = new javax.swing.JPanel();
                imgGrafica2 = new javax.swing.JLabel();
                lbResumenFinanciero = new javax.swing.JLabel();
                pResumenFinanciero = new javax.swing.JPanel();
                lbIngresosTotales = new javax.swing.JLabel();
                lbPonerIngresos = new javax.swing.JLabel();
                lbEgresosTotales = new javax.swing.JLabel();
                lbPonerEgresos = new javax.swing.JLabel();
                lbUtilidadNeta = new javax.swing.JLabel();
                lbPonerUtilidad = new javax.swing.JLabel();
                imgPDF = new javax.swing.JLabel();
                btnExportarPDF = new javax.swing.JButton();
                imgExcel = new javax.swing.JLabel();
                btnExportarExcel = new javax.swing.JButton();
                lbNotificaciones = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                panelFinancialReport.setBackground(new java.awt.Color(245, 245, 245));
                panelFinancialReport.setMaximumSize(new java.awt.Dimension(1467, 800));
                panelFinancialReport.setMinimumSize(new java.awt.Dimension(1467, 800));
                panelFinancialReport.setPreferredSize(new java.awt.Dimension(1467, 800));
                panelFinancialReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                pMenu.setBackground(new java.awt.Color(93, 0, 0));
                pMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbBackButton.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/back.png"))); // NOI18N
                lbBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbBackButtonMouseClicked(evt);
                        }
                });
                pMenu.add(lbBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

                panelFinancialReport.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 60));

                pGrafica1.setBackground(new java.awt.Color(245, 245, 245));
                pGrafica1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
                pGrafica1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                pGrafica1.add(imgGrafica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 340));

                panelFinancialReport.add(pGrafica1,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 430, 340));

                pGrafica2.setBackground(new java.awt.Color(245, 245, 245));
                pGrafica2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
                pGrafica2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                pGrafica2.add(imgGrafica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 340));

                panelFinancialReport.add(pGrafica2,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 430, 340));

                lbResumenFinanciero.setBackground(new java.awt.Color(0, 0, 0));
                lbResumenFinanciero.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbResumenFinanciero.setForeground(new java.awt.Color(20, 20, 20));
                lbResumenFinanciero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbResumenFinanciero.setText("Resumen Financiero");
                panelFinancialReport.add(lbResumenFinanciero,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 1180, 40));

                pResumenFinanciero.setBackground(new java.awt.Color(245, 245, 245));
                pResumenFinanciero.setBorder(
                                new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
                pResumenFinanciero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbIngresosTotales.setBackground(new java.awt.Color(0, 0, 0));
                lbIngresosTotales.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                lbIngresosTotales.setForeground(new java.awt.Color(20, 20, 20));
                lbIngresosTotales.setText("Ingresos Totales:");
                pResumenFinanciero.add(lbIngresosTotales,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

                lbPonerIngresos.setBackground(new java.awt.Color(0, 0, 0));
                lbPonerIngresos.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                lbPonerIngresos.setForeground(new java.awt.Color(51, 204, 0));
                lbPonerIngresos.setText("$300.000.000");
                pResumenFinanciero.add(lbPonerIngresos,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

                lbEgresosTotales.setBackground(new java.awt.Color(0, 0, 0));
                lbEgresosTotales.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                lbEgresosTotales.setForeground(new java.awt.Color(20, 20, 20));
                lbEgresosTotales.setText("Egresos Totales:");
                pResumenFinanciero.add(lbEgresosTotales,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

                lbPonerEgresos.setBackground(new java.awt.Color(0, 0, 0));
                lbPonerEgresos.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                lbPonerEgresos.setForeground(new java.awt.Color(255, 51, 51));
                lbPonerEgresos.setText("$100.000.000");
                pResumenFinanciero.add(lbPonerEgresos,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

                lbUtilidadNeta.setBackground(new java.awt.Color(0, 0, 0));
                lbUtilidadNeta.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                lbUtilidadNeta.setForeground(new java.awt.Color(20, 20, 20));
                lbUtilidadNeta.setText("Utilidad Neta:");
                pResumenFinanciero.add(lbUtilidadNeta,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

                lbPonerUtilidad.setBackground(new java.awt.Color(0, 0, 0));
                lbPonerUtilidad.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                lbPonerUtilidad.setForeground(new java.awt.Color(255, 204, 0));
                lbPonerUtilidad.setText("$100.000.000");
                pResumenFinanciero.add(lbPonerUtilidad,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

                panelFinancialReport.add(pResumenFinanciero,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 660, 140));

                imgPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/pdf.png"))); // NOI18N
                panelFinancialReport.add(imgPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 690, -1, 50));

                btnExportarPDF.setBackground(new java.awt.Color(93, 0, 0));
                btnExportarPDF.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                btnExportarPDF.setForeground(new java.awt.Color(200, 200, 200));
                btnExportarPDF.setText("Exportar a PDF");
                btnExportarPDF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnExportarPDF.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnExportarPDFActionPerformed(evt);
                        }
                });
                panelFinancialReport.add(btnExportarPDF,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 690, 250, 50));

                imgExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/excel.png"))); // NOI18N
                panelFinancialReport.add(imgExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 690, -1, 50));

                btnExportarExcel.setBackground(new java.awt.Color(93, 0, 0));
                btnExportarExcel.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                btnExportarExcel.setForeground(new java.awt.Color(200, 200, 200));
                btnExportarExcel.setText("Exportar a Excel");
                btnExportarExcel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnExportarExcel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnExportarExcelActionPerformed(evt);
                        }
                });
                panelFinancialReport.add(btnExportarExcel,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 690, 260, 50));

                lbNotificaciones.setBackground(new java.awt.Color(0, 0, 0));
                lbNotificaciones.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
                lbNotificaciones.setForeground(new java.awt.Color(93, 0, 0));
                lbNotificaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbNotificaciones.setText("Reportes Financieros");
                lbNotificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                panelFinancialReport.add(lbNotificaciones,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 1230, 50));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelFinancialReport, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelFinancialReport, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void lbBackButtonMouseClicked(java.awt.event.MouseEvent evt) {

                DashboardAdminScreen dashboard = new DashboardAdminScreen();
                dashboard.setVisible(true);
                this.setVisible(false);
        }

        private void btnExportarExcelActionPerformed(java.awt.event.ActionEvent evt) {

        }

        private void btnExportarPDFActionPerformed(java.awt.event.ActionEvent evt) {

        }

        public void graficaDistribucionMembresias(JLabel lbPonerGrafica) {
                // Crear la lista de clientes
                ClienteDAO dao = new ClienteDAO();
                List<Cliente> clientes = dao.obtenerTodos();

                // Variables para contar las distribuciones de cada tipo de membresía
                int membresia1Anio = 0;
                int membresia3Meses = 0;
                int membresia6Meses = 0;

                // Contar las membresías de los clientes
                for (Cliente cliente : clientes) {
                        switch (cliente.getTipoMembresia()) {
                        case "1 año":
                                membresia1Anio++;
                                break;
                        case "3 meses":
                                membresia3Meses++;
                                break;
                        case "6 meses":
                                membresia6Meses++;
                                break;
                        }
                }

                // Crear dataset para el gráfico circular
                DefaultPieDataset dataset = new DefaultPieDataset();
                dataset.setValue("1 Año", membresia1Anio);
                dataset.setValue("3 Meses", membresia3Meses);
                dataset.setValue("6 Meses", membresia6Meses);

                // Crear gráfico circular
                JFreeChart chart = createPieChart(dataset);

                // Convertir el gráfico a imagen y mostrar en JLabel
                BufferedImage image = chart.createBufferedImage(lbPonerGrafica.getWidth(), lbPonerGrafica.getHeight());
                lbPonerGrafica.setIcon(new ImageIcon(image));
        }

        private JFreeChart createPieChart(PieDataset dataset) {
                // Crear el gráfico de anillo (ring chart)
                JFreeChart chart = ChartFactory.createRingChart("Distribución de Membresías", dataset, true, true,
                                false);

                // ¡AQUÍ EL CAMBIO! Hacemos cast a RingPlot, no a PiePlot
                RingPlot plot = (RingPlot) chart.getPlot();

                plot.setSectionDepth(0.30); // Profundidad de los sectores
                plot.setSectionPaint("1 Año", new Color(79, 129, 189));
                plot.setSectionPaint("3 Meses", new Color(0, 128, 0));
                plot.setSectionPaint("6 Meses", new Color(255, 165, 0));

                return chart;
        }

        public void graficaIngresosVsEgresos(JLabel lbPonerGrafica) {
                ContabilidadDAO dao = new ContabilidadDAO();
                List<Contabilidad> registros = dao.obtenerTodos();

                double totalIngresos = 0;
                double totalEgresos = 0;

                for (Contabilidad c : registros) {
                        totalIngresos += c.getIngresos();
                        totalEgresos += c.getEgresos();
                }

                // Crear dataset para gráfico de barras
                DefaultCategoryDataset dataset = new DefaultCategoryDataset();
                dataset.setValue(totalIngresos, "Monto", "Ingresos");
                dataset.setValue(totalEgresos, "Monto", "Egresos");

                // Crear gráfico
                JFreeChart chart = ChartFactory.createBarChart("Ingresos vs Egresos", // título
                                "Categoría", // eje X
                                "Monto", // eje Y
                                dataset);

                // Personalizar colores del gráfico
                CategoryPlot plot = chart.getCategoryPlot();
                BarRenderer renderer = (BarRenderer) plot.getRenderer();
                renderer.setSeriesPaint(0, new Color(79, 129, 189)); // azul

                // Convertir el gráfico a imagen y mostrar en JLabel
                BufferedImage image = chart.createBufferedImage(lbPonerGrafica.getWidth(), lbPonerGrafica.getHeight());
                lbPonerGrafica.setIcon(new ImageIcon(image));
        }

        public void ponerInformacion() {
                ContabilidadDAO dao = new ContabilidadDAO();
                List<Contabilidad> registros = dao.obtenerTodos();

                double totalIngresos = 0;
                double totalEgresos = 0;

                for (Contabilidad c : registros) {
                        totalIngresos += c.getIngresos();
                        totalEgresos += c.getEgresos();
                }
                CambiarIU.ponerTextoEtiqueta(lbPonerIngresos, String.valueOf(totalIngresos));
                CambiarIU.ponerTextoEtiqueta(lbPonerEgresos, String.valueOf(totalEgresos));
                CambiarIU.ponerTextoEtiqueta(lbPonerUtilidad, String.valueOf((totalIngresos - totalEgresos)));

        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnExportarExcel;
        private javax.swing.JButton btnExportarPDF;
        private javax.swing.JLabel imgExcel;
        private javax.swing.JLabel imgGrafica1;
        private javax.swing.JLabel imgGrafica2;
        private javax.swing.JLabel imgPDF;
        private javax.swing.JLabel lbBackButton;
        private javax.swing.JLabel lbEgresosTotales;
        private javax.swing.JLabel lbIngresosTotales;
        private javax.swing.JLabel lbNotificaciones;
        private javax.swing.JLabel lbPonerEgresos;
        private javax.swing.JLabel lbPonerIngresos;
        private javax.swing.JLabel lbPonerUtilidad;
        private javax.swing.JLabel lbResumenFinanciero;
        private javax.swing.JLabel lbUtilidadNeta;
        private javax.swing.JPanel pGrafica1;
        private javax.swing.JPanel pGrafica2;
        private javax.swing.JPanel pMenu;
        private javax.swing.JPanel pResumenFinanciero;
        private javax.swing.JPanel panelFinancialReport;
        // End of variables declaration//GEN-END:variables
}
