// cSpell:ignore grafica distribucion membresias egresos informacion Márgen membresia simbolos
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.Gym360.view.admin;

import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

import main.java.com.Gym360.model.classes.Cliente;
import main.java.com.Gym360.model.classes.Contabilidad;
import main.java.com.Gym360.model.dao.ClienteDAO;
import main.java.com.Gym360.model.dao.ContabilidadDAO;
import main.java.com.Gym360.util.ui.CambiarIU;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.StandardChartTheme;
import org.jfree.chart.labels.StandardPieToolTipGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PieLabelLinkStyle;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.RingPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.GradientBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;

/**
 *
 * @author tutaa
 */
public class FinancialReportScreen extends javax.swing.JFrame {

	/**
	 * Creates new form FinancialReportScreen
	 */
	public FinancialReportScreen() {
		initComponents();
		this.setTitle("Reportes Financieros");
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setIconImage(
				Toolkit.getDefaultToolkit().getImage(getClass().getResource("/main/resources/images/logo.png")));
		graficaIngresosVsEgresos(imgGrafica1);
		graficaDistribucionMembresias(imgGrafica2);
		ponerInformacion();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		panelFinancialReport = new javax.swing.JPanel();
		pMenu = new javax.swing.JPanel();
		lbBackButton = new javax.swing.JLabel();
		pGrafica1 = new javax.swing.JPanel();
		imgGrafica1 = new javax.swing.JLabel();
		pGrafica2 = new javax.swing.JPanel();
		imgGrafica2 = new javax.swing.JLabel();
		lbResumenFinanciero = new javax.swing.JLabel();
		pResumenFinanciero = new javax.swing.JPanel();
		lbIngresosTotales = new javax.swing.JLabel();
		lbPonerIngresos = new javax.swing.JLabel();
		lbEgresosTotales = new javax.swing.JLabel();
		lbPonerEgresos = new javax.swing.JLabel();
		lbUtilidadNeta = new javax.swing.JLabel();
		lbPonerUtilidad = new javax.swing.JLabel();
		lbMargenUtilidad = new javax.swing.JLabel();
		lbPonerMargenUtilidad = new javax.swing.JLabel();
		imgPDF = new javax.swing.JLabel();
		btnExportarPDF = new javax.swing.JButton();
		imgExcel = new javax.swing.JLabel();
		btnExportarExcel = new javax.swing.JButton();
		lbNotificaciones = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		panelFinancialReport.setBackground(new java.awt.Color(245, 245, 245));
		panelFinancialReport.setMaximumSize(new java.awt.Dimension(1467, 800));
		panelFinancialReport.setMinimumSize(new java.awt.Dimension(1467, 800));
		panelFinancialReport.setPreferredSize(new java.awt.Dimension(1467, 800));
		panelFinancialReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		pMenu.setBackground(new java.awt.Color(93, 0, 0));
		pMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		lbBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/back.png"))); // NOI18N
		lbBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		lbBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				lbBackButtonMouseClicked(evt);
			}
		});
		pMenu.add(lbBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

		panelFinancialReport.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 60));

		pGrafica1.setBackground(new java.awt.Color(245, 245, 245));
		pGrafica1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
		pGrafica1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
		pGrafica1.add(imgGrafica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 340));

		panelFinancialReport.add(pGrafica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 430, 340));

		pGrafica2.setBackground(new java.awt.Color(245, 245, 245));
		pGrafica2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
		pGrafica2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
		pGrafica2.add(imgGrafica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 340));

		panelFinancialReport.add(pGrafica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 430, 340));

		lbResumenFinanciero.setBackground(new java.awt.Color(0, 0, 0));
		lbResumenFinanciero.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
		lbResumenFinanciero.setForeground(new java.awt.Color(20, 20, 20));
		lbResumenFinanciero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lbResumenFinanciero.setText("Resumen Financiero");
		panelFinancialReport.add(lbResumenFinanciero,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 1180, 40));

		pResumenFinanciero.setBackground(new java.awt.Color(245, 245, 245));
		pResumenFinanciero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
		pResumenFinanciero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		lbIngresosTotales.setBackground(new java.awt.Color(0, 0, 0));
		lbIngresosTotales.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
		lbIngresosTotales.setForeground(new java.awt.Color(20, 20, 20));
		lbIngresosTotales.setText("Ingresos Totales:");
		pResumenFinanciero.add(lbIngresosTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

		lbPonerIngresos.setBackground(new java.awt.Color(0, 0, 0));
		lbPonerIngresos.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
		lbPonerIngresos.setForeground(new java.awt.Color(51, 204, 0));
		lbPonerIngresos.setText("$300.000.000");
		pResumenFinanciero.add(lbPonerIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 170, -1));

		lbEgresosTotales.setBackground(new java.awt.Color(0, 0, 0));
		lbEgresosTotales.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
		lbEgresosTotales.setForeground(new java.awt.Color(20, 20, 20));
		lbEgresosTotales.setText("Egresos Totales:");
		pResumenFinanciero.add(lbEgresosTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

		lbPonerEgresos.setBackground(new java.awt.Color(0, 0, 0));
		lbPonerEgresos.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
		lbPonerEgresos.setForeground(new java.awt.Color(255, 51, 51));
		lbPonerEgresos.setText("$100.000.000");
		pResumenFinanciero.add(lbPonerEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 30, 170, -1));

		lbUtilidadNeta.setBackground(new java.awt.Color(0, 0, 0));
		lbUtilidadNeta.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
		lbUtilidadNeta.setForeground(new java.awt.Color(20, 20, 20));
		lbUtilidadNeta.setText("Utilidad Neta:");
		pResumenFinanciero.add(lbUtilidadNeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

		lbPonerUtilidad.setBackground(new java.awt.Color(0, 0, 0));
		lbPonerUtilidad.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
		lbPonerUtilidad.setForeground(new java.awt.Color(255, 204, 0));
		lbPonerUtilidad.setText("$100.000.000");
		pResumenFinanciero.add(lbPonerUtilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 180, -1));

		lbMargenUtilidad.setBackground(new java.awt.Color(0, 0, 0));
		lbMargenUtilidad.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
		lbMargenUtilidad.setForeground(new java.awt.Color(20, 20, 20));
		lbMargenUtilidad.setText("Márgen de Utilidad Neta:");
		pResumenFinanciero.add(lbMargenUtilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

		lbPonerMargenUtilidad.setBackground(new java.awt.Color(0, 0, 0));
		lbPonerMargenUtilidad.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
		lbPonerMargenUtilidad.setForeground(new java.awt.Color(255, 204, 0));
		lbPonerMargenUtilidad.setText("$100.000.000");
		pResumenFinanciero.add(lbPonerMargenUtilidad,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, -1));

		panelFinancialReport.add(pResumenFinanciero,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 700, 170));

		imgPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/pdf.png"))); // NOI18N
		panelFinancialReport.add(imgPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 660, -1, 50));

		btnExportarPDF.setBackground(new java.awt.Color(93, 0, 0));
		btnExportarPDF.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
		btnExportarPDF.setForeground(new java.awt.Color(200, 200, 200));
		btnExportarPDF.setText("Exportar a PDF");
		btnExportarPDF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		btnExportarPDF.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExportarPDFActionPerformed(evt);
			}
		});
		panelFinancialReport.add(btnExportarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 660, 250, 50));

		imgExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/excel.png"))); // NOI18N
		panelFinancialReport.add(imgExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 660, -1, 50));

		btnExportarExcel.setBackground(new java.awt.Color(93, 0, 0));
		btnExportarExcel.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
		btnExportarExcel.setForeground(new java.awt.Color(200, 200, 200));
		btnExportarExcel.setText("Exportar a Excel");
		btnExportarExcel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		btnExportarExcel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExportarExcelActionPerformed(evt);
			}
		});
		panelFinancialReport.add(btnExportarExcel,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 660, 260, 50));

		lbNotificaciones.setBackground(new java.awt.Color(0, 0, 0));
		lbNotificaciones.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
		lbNotificaciones.setForeground(new java.awt.Color(93, 0, 0));
		lbNotificaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lbNotificaciones.setText("Reportes Financieros");
		lbNotificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		panelFinancialReport.add(lbNotificaciones,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 1230, 50));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(panelFinancialReport,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(panelFinancialReport,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void lbBackButtonMouseClicked(java.awt.event.MouseEvent evt) {

		DashboardAdminScreen dashboard = new DashboardAdminScreen();
		dashboard.setVisible(true);
		this.setVisible(false);
	}

	private void btnExportarExcelActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void btnExportarPDFActionPerformed(java.awt.event.ActionEvent evt) {

	}

	// Tema general con degradados y fuentes
	private static void aplicarTema(JFreeChart chart) {
		StandardChartTheme theme = (StandardChartTheme) StandardChartTheme.createJFreeTheme();
		theme.setExtraLargeFont(new Font("SansSerif", Font.BOLD, 20));
		theme.setLargeFont(new Font("SansSerif", Font.PLAIN, 14));
		theme.setRegularFont(new Font("SansSerif", Font.PLAIN, 12));
		theme.setChartBackgroundPaint(new GradientPaint(0, 0, Color.white, 400, 200, new Color(230, 230, 255)));
		theme.setPlotBackgroundPaint(new GradientPaint(0, 0, Color.white, 400, 200, new Color(255, 245, 230)));
		// no afecta si la leyenda está desactivada
		theme.apply(chart);
	}

	// Gráfica de distribución de membresías (anillo vistoso) sin leyenda
	public static void graficaDistribucionMembresias(JLabel lbPonerGrafica) {
		ClienteDAO dao = new ClienteDAO();
		List<Cliente> clientes = dao.obtenerTodos();

		int membresia1Año = 0, membresia3Meses = 0, membresia6Meses = 0;
		for (Cliente c : clientes) {
			switch (c.getTipoMembresia()) {
			case "1 año":
				membresia1Año++;
				break;
			case "3 meses":
				membresia3Meses++;
				break;
			case "6 meses":
				membresia6Meses++;
				break;
			}
		}

		DefaultPieDataset dataset = new DefaultPieDataset();
		dataset.setValue("1 Año", membresia1Año);
		dataset.setValue("3 Meses", membresia3Meses);
		dataset.setValue("6 Meses", membresia6Meses);

		JFreeChart chart = createFancyRingChart(dataset);
		BufferedImage image = chart.createBufferedImage(lbPonerGrafica.getWidth(), lbPonerGrafica.getHeight());
		lbPonerGrafica.setIcon(new ImageIcon(image));
	}

	private static JFreeChart createFancyRingChart(PieDataset dataset) {
		// legend = false
		JFreeChart chart = ChartFactory.createRingChart("Distribución de Membresías", // título
				dataset, // dataset
				false, // ¡sin leyenda!
				true, // tooltips
				false // URLs
		);

		RingPlot plot = (RingPlot) chart.getPlot();
		plot.setSectionDepth(0.35);
		plot.setShadowPaint(new Color(0, 0, 0, 80));
		plot.setShadowXOffset(5);
		plot.setShadowYOffset(5);
		plot.setOutlineVisible(false);

		Color[] paleta = { new Color(0x2196F3), new Color(0x4CAF50), new Color(0xFFC107) };
		plot.setSectionPaint("1 Año", paleta[0]);
		plot.setSectionPaint("3 Meses", paleta[1]);
		plot.setSectionPaint("6 Meses", paleta[2]);

		plot.setSimpleLabels(true);
		plot.setLabelFont(new Font("SansSerif", Font.BOLD, 14));
		plot.setLabelLinkStyle(PieLabelLinkStyle.CUBIC_CURVE);
		plot.setLabelBackgroundPaint(new Color(255, 255, 255, 200));
		plot.setToolTipGenerator(new StandardPieToolTipGenerator("{0}: {1} ({2})", NumberFormat.getNumberInstance(),
				new DecimalFormat("0.00%")));

		aplicarTema(chart);
		return chart;
	}

	// Gráfica de Ingresos vs Egresos (barras con gradientes y sombras) sin leyenda
	public static void graficaIngresosVsEgresos(JLabel lbPonerGrafica) {
		ContabilidadDAO dao = new ContabilidadDAO();
		List<Contabilidad> registros = dao.obtenerTodos();

		double totalIngresos = 0, totalEgresos = 0;
		for (Contabilidad c : registros) {
			totalIngresos += c.getIngresos();
			totalEgresos += c.getEgresos();
		}

		DefaultCategoryDataset dataset = new DefaultCategoryDataset();
		dataset.setValue(totalIngresos, "Monto", "Ingresos");
		dataset.setValue(totalEgresos, "Monto", "Egresos");

		JFreeChart chart = ChartFactory.createBarChart("Ingresos vs Egresos", // título
				"Categoría", // eje X
				"Monto", // eje Y
				dataset, // datos
				PlotOrientation.VERTICAL, // orientación
				false, // ¡sin leyenda!
				true, // tooltips
				false // URLs
		);

		CategoryPlot plot = chart.getCategoryPlot();
		BarRenderer renderer = (BarRenderer) plot.getRenderer();
		renderer.setBarPainter(new GradientBarPainter(0.1, 0.5, 0.1));
		renderer.setShadowVisible(true);
		renderer.setShadowXOffset(4);
		renderer.setShadowYOffset(4);
		renderer.setMaximumBarWidth(0.15);
		renderer.setSeriesPaint(0, new Color(0x2196F3));
		renderer.setDrawBarOutline(false);

		plot.getDomainAxis().setLabelFont(new Font("SansSerif", Font.BOLD, 14));
		plot.getRangeAxis().setLabelFont(new Font("SansSerif", Font.BOLD, 14));
		plot.setOutlineVisible(false);

		aplicarTema(chart);
		BufferedImage image = chart.createBufferedImage(lbPonerGrafica.getWidth(), lbPonerGrafica.getHeight());
		lbPonerGrafica.setIcon(new ImageIcon(image));
	}

	public void ponerInformacion() {
		ContabilidadDAO dao = new ContabilidadDAO();
		List<Contabilidad> registros = dao.obtenerTodos();

		double totalIngresos = 0;
		double totalEgresos = 0;

		for (Contabilidad c : registros) {
			totalIngresos += c.getIngresos();
			totalEgresos += c.getEgresos();
		}

		DecimalFormatSymbols simbolos = new DecimalFormatSymbols(new Locale("es", "CO"));
		simbolos.setGroupingSeparator(','); // separador de miles como guión bajo
		simbolos.setDecimalSeparator('.'); // separador decimal como coma

		DecimalFormat formato = new DecimalFormat("#,##0.0", simbolos);

		// Mostrar Ingresos y Egresos
		CambiarIU.ponerTextoEtiqueta(lbPonerIngresos, String.valueOf(formato.format(totalIngresos)));
		CambiarIU.ponerTextoEtiqueta(lbPonerEgresos, String.valueOf(formato.format(totalEgresos)));

		// Calcular Utilidad
		double utilidad = totalIngresos - totalEgresos;
		CambiarIU.ponerTextoEtiqueta(lbPonerUtilidad, String.valueOf(formato.format(utilidad)));

		// Calcular Margen de Utilidad
		String margenTexto;
		if (totalIngresos != 0) {
			int margen = (int) ((utilidad / totalIngresos) * 100);
			margenTexto = margen + "%";
		} else {
			margenTexto = "0%";
		}
		CambiarIU.ponerTextoEtiqueta(lbPonerMargenUtilidad, margenTexto);

		// Cambiar color dependiendo del resultado
		Color colorPositivo = new Color(0, 153, 0); // verde
		Color colorNegativo = Color.RED;
		Color colorNeutro = Color.GRAY;

		Color colorFinal;

		if (utilidad > 0) {
			colorFinal = colorPositivo;
		} else if (utilidad < 0) {
			colorFinal = colorNegativo;
		} else {
			colorFinal = colorNeutro;
		}

		// Aplicar el color a las etiquetas clave
		lbPonerUtilidad.setForeground(colorFinal);
		lbPonerMargenUtilidad.setForeground(colorFinal);
		lbPonerIngresos.setForeground(totalIngresos >= totalEgresos ? colorPositivo : colorNegativo);
		lbPonerEgresos.setForeground(totalEgresos > totalIngresos ? colorNegativo : colorPositivo);

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnExportarExcel;
	private javax.swing.JButton btnExportarPDF;
	private javax.swing.JLabel imgExcel;
	private javax.swing.JLabel imgGrafica1;
	private javax.swing.JLabel imgGrafica2;
	private javax.swing.JLabel imgPDF;
	private javax.swing.JLabel lbBackButton;
	private javax.swing.JLabel lbEgresosTotales;
	private javax.swing.JLabel lbIngresosTotales;
	private javax.swing.JLabel lbMargenUtilidad;
	private javax.swing.JLabel lbNotificaciones;
	private javax.swing.JLabel lbPonerEgresos;
	private javax.swing.JLabel lbPonerIngresos;
	private javax.swing.JLabel lbPonerMargenUtilidad;
	private javax.swing.JLabel lbPonerUtilidad;
	private javax.swing.JLabel lbResumenFinanciero;
	private javax.swing.JLabel lbUtilidadNeta;
	private javax.swing.JPanel pGrafica1;
	private javax.swing.JPanel pGrafica2;
	private javax.swing.JPanel pMenu;
	private javax.swing.JPanel pResumenFinanciero;
	private javax.swing.JPanel panelFinancialReport;
	// End of variables declaration//GEN-END:variables
}
