/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.Gym360.view.admin.users;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.EventQueue;
import java.awt.Toolkit;
import javax.swing.UIManager;

/**
 *
 * @author tutaa
 */
public class CreateUser extends javax.swing.JFrame {

	/**
	 * Creates new form ManageUsersScreen
	 */
	public CreateUser() {
		initComponents();
		this.setTitle("Crear Usuario");
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/main/resources/images/logo.png")));
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelCrearUsuario = new javax.swing.JPanel();
                pMenu = new javax.swing.JPanel();
                lbBackButton = new javax.swing.JLabel();
                lbCrearUsuario = new javax.swing.JLabel();
                lbNombre = new javax.swing.JLabel();
                tfNombre = new javax.swing.JTextField();
                lbCargo = new javax.swing.JLabel();
                tfCargo = new javax.swing.JTextField();
                lbContraseña = new javax.swing.JLabel();
                tfContraseña = new javax.swing.JTextField();
                imgCrearUsuario = new javax.swing.JLabel();
                btnCrearUsuario = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                panelCrearUsuario.setBackground(new java.awt.Color(245, 245, 245));
                panelCrearUsuario.setMaximumSize(new java.awt.Dimension(1467, 800));
                panelCrearUsuario.setMinimumSize(new java.awt.Dimension(1467, 800));
                panelCrearUsuario.setPreferredSize(new java.awt.Dimension(1467, 800));
                panelCrearUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                pMenu.setBackground(new java.awt.Color(93, 0, 0));
                pMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/back.png"))); // NOI18N
                lbBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lbBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbBackButtonMouseClicked(evt);
                        }
                });
                pMenu.add(lbBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

                lbCrearUsuario.setBackground(new java.awt.Color(0, 0, 0));
                lbCrearUsuario.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
                lbCrearUsuario.setForeground(new java.awt.Color(245, 245, 245));
                lbCrearUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbCrearUsuario.setText("AGREGAR USUARIO");
                lbCrearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                pMenu.add(lbCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

                panelCrearUsuario.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

                lbNombre.setBackground(new java.awt.Color(0, 0, 0));
                lbNombre.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbNombre.setForeground(new java.awt.Color(20, 20, 20));
                lbNombre.setText("Nombre:");
                panelCrearUsuario.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, 40));

                tfNombre.setBackground(new java.awt.Color(231, 231, 231));
                tfNombre.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfNombre.setForeground(new java.awt.Color(20, 20, 20));
                tfNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                panelCrearUsuario.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 280, 40));

                lbCargo.setBackground(new java.awt.Color(0, 0, 0));
                lbCargo.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbCargo.setForeground(new java.awt.Color(20, 20, 20));
                lbCargo.setText("Cargo:");
                panelCrearUsuario.add(lbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 40));

                tfCargo.setBackground(new java.awt.Color(231, 231, 231));
                tfCargo.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfCargo.setForeground(new java.awt.Color(20, 20, 20));
                tfCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                panelCrearUsuario.add(tfCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 280, 40));

                lbContraseña.setBackground(new java.awt.Color(0, 0, 0));
                lbContraseña.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lbContraseña.setForeground(new java.awt.Color(20, 20, 20));
                lbContraseña.setText("Contraseña:");
                panelCrearUsuario.add(lbContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, 40));

                tfContraseña.setBackground(new java.awt.Color(231, 231, 231));
                tfContraseña.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
                tfContraseña.setForeground(new java.awt.Color(20, 20, 20));
                tfContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                panelCrearUsuario.add(tfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 280, 40));

                imgCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/agregarUsuario.png"))); // NOI18N
                panelCrearUsuario.add(imgCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 40, 60));

                btnCrearUsuario.setBackground(new java.awt.Color(93, 0, 0));
                btnCrearUsuario.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
                btnCrearUsuario.setForeground(new java.awt.Color(200, 200, 200));
                btnCrearUsuario.setText("      Agregar Usuario");
                btnCrearUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCrearUsuarioActionPerformed(evt);
                        }
                });
                panelCrearUsuario.add(btnCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 300, 60));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_btnCrearUsuarioActionPerformed

        private void lbBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackButtonMouseClicked
                // TODO add your handling code here:
		ManageUsersScreen mu = new ManageUsersScreen();
		mu.setVisible(true);
		this.setVisible(false);
        }//GEN-LAST:event_lbBackButtonMouseClicked

	/**
	 * @param args the command line arguments
	 */
	
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCrearUsuario;
        private javax.swing.JLabel imgCrearUsuario;
        private javax.swing.JLabel lbBackButton;
        private javax.swing.JLabel lbCargo;
        private javax.swing.JLabel lbContraseña;
        private javax.swing.JLabel lbCrearUsuario;
        private javax.swing.JLabel lbNombre;
        private javax.swing.JPanel pMenu;
        private javax.swing.JPanel panelCrearUsuario;
        private javax.swing.JTextField tfCargo;
        private javax.swing.JTextField tfContraseña;
        private javax.swing.JTextField tfNombre;
        // End of variables declaration//GEN-END:variables
}
